objects/Address__c.object
<CustomObject>
    <description>VOLO - 
Custom address object to accommodate account to addresses relation.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Region</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Sub-Region</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>PS Orders</relationshipLabel>
        <relationshipName>PS_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PS Order</label>
    <nameField>
        <displayFormat>Ord-{000000}</displayFormat>
        <label>Order Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Class__c.object
<CustomObject>
    <label>Product Class</label>
    <nameField>
        <label>Product Class Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>Optional__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Solutions</relationshipLabel>
        <relationshipName>Quote_Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Solution</label>
    <nameField>
        <label>Quote Solutions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Line_Matrix__c.object
<CustomObject>
    <description>VOLO
--
Service Line matrix used by quote process in order to identify matching support and professional support part number</description>
    <fields>
        <fullName>Percent_of_Line_Total_Product_Line__c</fullName>
        <label>Percent of Line Total/ Product Line</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Class</label>
        <referenceTo>Product_Class__c</referenceTo>
        <relationshipLabel>Service Lines Matrix</relationshipLabel>
        <relationshipName>Service_Lines_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Professional_Service_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Professional Service Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Product_Group__c</field>
                <operation>startsWith</operation>
                <value>Professional Services</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Lines Matrix (Professional Service Product)</relationshipLabel>
        <relationshipName>Service_Lines_Matrix1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Salesforce_Product_Type__c</field>
                <operation>equals</operation>
                <value>Support</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Lines Matrix</relationshipLabel>
        <relationshipName>Service_Lines_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Type__c</fullName>
        <label>Support Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Care</fullName>
                </value>
                <value>
                    <fullName>Care Plus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Line Matrix</label>
    <nameField>
        <displayFormat>SERV-{000000}</displayFormat>
        <label>Service Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Lines Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PopulateQuoteDiscountsTest.cls
@isTest(SeeAllData = true)
public class PopulateQuoteDiscountsTest {
    private testmethod static void discountTest1(){
        QuoteLineItemTriggerManager.ALLOWTRIGGERPROCESS = true;
        test.startTest();
        Account testAccount = new Account(Name = 'test Account',Type ='Prospect');
        insert testAccount;
        Country__c cty = new Country__c(Name = 'United States of America', Global_Region__c = 'NORTH AMERICA', Region__c = 'US', Country__c = 'United States of America');
        insert cty;
        Address__c testAddress = TestDataFactory.createAddress(testAccount);
        
        Pricebook2 pb = [select Id from Pricebook2 where isActive = true and Name='Canadian Domestic List Prices (CAD)'];
       
        Opportunity testOpportunity = new Opportunity(Name = 'test Opportunity',Pricebook2Id=pb.id,AccountId=testAccount.Id, StageName='Prospecting',CloseDate = Date.today()+30, Description = 'testing' );
        insert testOpportunity;

        Quote testQuote = new Quote(Name = 'test QuoteOptional', Hardware_Discount__c=1.0,OpportunityId = testOpportunity.Id,Default_Price_Book__c=pb.id, Tier_Discount2__c = 20);  
        insert testQuote;
        
        Quote_Solutions__c qs1 = new Quote_Solutions__c(Name='Master Quote Solution', Order__c = 1.0, Quote__c = testQuote.id,Optional__c = true);
        insert qs1;
        
        List<String> productLineList = new List<String>();
        productLineList.add('DOH');
        productLineList.add('Signaling & Transcoding');
        
        productLineList.add('Professional Services');
        productLineList.add('Support');
        List<Product_Class__c> productClassList = new List<Product_Class__c>();

        for(String productLine : productLineList){
            Product_Class__c pClass = TestDataFactory.initProductClass(productLine);
            if(pClass != null){
                productClassList.add(pClass);
            }
        }
        insert productClassList;
        List<QuoteLineItem> quoteLineItemList = new List<QuoteLineItem>();
        Product2 prod3 = new Product2(Name='test product 3', NonDiscountable__c =  false,ProductCode='FRINKSF', Product_Type__c='Professional Services',Salesforce_Product_Type__c = 'Hardware', Product_Class__c = productClassList[0].Id);
        Product2 prod6 = new Product2(Name='support product 1',NonDiscountable__c =  false, ProductCode='SUP', Product_Type__c = 'Support', Salesforce_Product_Type__c = 'Support', Product_Class__c = productClassList[0].Id   );
        insert prod3;
        insert prod6;
        
        Service_Line_Matrix__c sl = new Service_Line_Matrix__c();
        sl.Product_Class__c = productClassList[0].Id;
        sl.Product_Type__c = 'Hardware';
        sl.Professional_Service_Product__c = prod3.Id;
        sl.Support_Product__c = prod6.Id;
        sl.Support_Type__c = 'Care';
        sl.Percent_of_Line_Total_Product_Line__c = 11;
        insert sl;
        
        
        for(Product_Class__c productClass : productClassList){
            QuoteLineItem item = QuoteLineMainTest.createQuoteLineItem(productClass,testQuote.Id,pb.id,10,100);
            if(item != null){
                quoteLineItemList.add(item);
            }
        }
        for(Product_Class__c productClass : productClassList){
            QuoteLineItem item = QuoteLineMainTest.createQuoteLineItem(productClass,testQuote.Id,pb.id,10,100, 'OEM', 'Hardware');
            if(item != null){
                quoteLineItemList.add(item);
            }
        }

        for(Product_Class__c productClass : productClassList){
            QuoteLineItem item = QuoteLineMainTest.createQuoteLineItem(productClass,testQuote.Id,pb.id,10,100, 'OEM', 'support');
            if(item != null){
                quoteLineItemList.add(item);
            }
        }

        for(Product_Class__c productClass : productClassList){
            QuoteLineItem item = QuoteLineMainTest.createQuoteLineItem(productClass,testQuote.Id,pb.id,10,100, 'OEM', 'service');
            if(item != null){
                quoteLineItemList.add(item);
            }
        }

        for(Product_Class__c productClass : productClassList){
            QuoteLineItem item = QuoteLineMainTest.createQuoteLineItem(productClass,testQuote.Id,pb.id,10,100, 'OEM', 'Software');
            if(item != null){
                quoteLineItemList.add(item);
            }
        }
        insert quoteLineItemList;
        PopulateQuoteDiscounts.populateDiscounts(new List<Id> {testQuote.Id});

        PageReference pageRef = Page.QuoteDiscountBatchStatus;
        Test.setCurrentPage(pageRef);
        Quote batchQuote = [SELECT id,Discount_Batch_Id__c FROM Quote WHERE id =:testQuote.id];
        pageRef.getParameters().put('Id', String.valueOf(batchQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(batchQuote);
        QuoteBatchStatusExtension qbsExt = new QuoteBatchStatusExtension(sc);
        qbsExt.checkStatus();
        test.stopTest();
    }
    private testmethod static void discountTest2(){
        QuoteLineItemTriggerManager.ALLOWTRIGGERPROCESS = true;
        test.startTest();
        Account testAccount = new Account(Name = 'test Account',Type ='Prospect');
        insert testAccount;
        Country__c cty = new Country__c(Name = 'United States of America', Global_Region__c = 'NORTH AMERICA', Region__c = 'US', Country__c = 'United States of America');
        insert cty;
        Address__c testAddress = TestDataFactory.createAddress(testAccount);
        
        Pricebook2 pb = [select Id from Pricebook2 where isActive = true and Name='Canadian Domestic List Prices (CAD)'];
       
        Opportunity testOpportunity = new Opportunity(Name = 'test Opportunity',Pricebook2Id=pb.id,AccountId=testAccount.Id, StageName='Prospecting',CloseDate = Date.today()+30, Description = 'testing' );
        insert testOpportunity;

        Quote testQuote = new Quote(Name = 'test QuoteOptional', Hardware_Discount__c=1.0,OpportunityId = testOpportunity.Id,Default_Price_Book__c=pb.id, Tier_Discount2__c = 20);  
        insert testQuote;
        
        Quote_Solutions__c qs1 = new Quote_Solutions__c(Name='Master Quote Solution', Order__c = 1.0, Quote__c = testQuote.id,Optional__c = true);
        insert qs1;
        
        List<String> productLineList = new List<String>();
        productLineList.add('DOH');
        productLineList.add('Signaling & Transcoding');
        
        productLineList.add('Professional Services');
        productLineList.add('Support');
        List<Product_Class__c> productClassList = new List<Product_Class__c>();

        for(String productLine : productLineList){
            Product_Class__c pClass = TestDataFactory.initProductClass(productLine);
            if(pClass != null){
                productClassList.add(pClass);
            }
        }
        insert productClassList;
        List<QuoteLineItem> quoteLineItemList = new List<QuoteLineItem>();
        
        Product2 prod3 = new Product2(Name='test product 3', NonDiscountable__c =  false,ProductCode='FRINKSF', Product_Type__c='Professional Services',Salesforce_Product_Type__c = 'Hardware', Product_Class__c = productClassList[0].Id);
        Product2 prod6 = new Product2(Name='support product 1',NonDiscountable__c =  false, ProductCode='SUP', Product_Type__c = 'Support', Salesforce_Product_Type__c = 'Support', Product_Class__c = productClassList[0].Id   );
        insert prod3;
        insert prod6;
        
        Service_Line_Matrix__c sl = new Service_Line_Matrix__c();
        sl.Product_Class__c = productClassList[0].Id;
        sl.Product_Type__c = 'Hardware';
        sl.Professional_Service_Product__c = prod3.Id;
        sl.Support_Product__c = prod6.Id;
        sl.Support_Type__c = 'Care';
        sl.Percent_of_Line_Total_Product_Line__c = 11;
        insert sl;
        
        
        for(Product_Class__c productClass : productClassList){
            QuoteLineItem item = QuoteLineMainTest.createQuoteLineItem(productClass,testQuote.Id,pb.id,10,100);
            if(item != null){
                quoteLineItemList.add(item);
            }
        }
        insert quoteLineItemList;
        QuoteDiscountBatch qdb = new QuoteDiscountBatch(new Set<Id> {testQuote.Id});
        Id batchId = Database.executeBatch(qdb, 10);

        PageReference pageRef = Page.QuoteDiscountBatchStatus;
        Test.setCurrentPage(pageRef);
        Quote batchQuote = [SELECT id,Discount_Batch_Id__c FROM Quote WHERE id =:testQuote.id];
        batchQuote.Discount_Batch_Id__c = batchId;
        update batchQuote;
        pageRef.getParameters().put('Id', String.valueOf(batchQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(batchQuote);
        QuoteBatchStatusExtension qbsExt = new QuoteBatchStatusExtension(sc);
        qbsExt.checkStatus();
        test.stopTest();
    }
}