objects/Address__c.object
<CustomObject>
    <description>VOLO - 
Custom address object to accommodate account to addresses relation.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Deprecated</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses (Deprecated)</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Oracle_Address_ID__c</fullName>
        <description>The discrepancy from Label to Name is due to changes in R12 integration. The name was kept to preserve integration functionality, the label represents the correct data element.</description>
        <externalId>true</externalId>
        <label>Oracle PSITE  ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusinessHourTempStore__c.object
<CustomObject>
    <description>Administrative object to help handle BusinessHours Integration</description>
    <fields>
        <fullName>Business_Hours_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Hours ID</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>BusinessHourTempStores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CoverageFriday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CoverageFriday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CoverageMonnday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CoverageMonnday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CoverageSaturday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CoverageSaturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CoverageSunday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CoverageSunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CoverageThursday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CoverageThursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CoverageTuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CoverageTuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CoverageWednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CoverageWednesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>EndTime</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Id__c</fullName>
        <externalId>true</externalId>
        <label>Integration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TimeZoneSIDKey__c</fullName>
        <label>TimeZoneSIDKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BusinessHourTempStore</label>
    <nameField>
        <displayFormat>BH-{0000000000}</displayFormat>
        <label>BusinessHourTempStoreNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BusinessHourTempStores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceCloudSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Administrative settings for the service cloud deployment</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ServiceCloudSettings</label>
</CustomObject>

classes/test_ServiceContract.cls
@isTest
(seeAllData=true)
public class test_ServiceContract {
    public static string getIntegrationId(BusinessHours bh){
        /*
        CONCAT( 
            CONCAT( 
                IIF( TimeZoneSidKey='America/New_York', '-05', 
                    IIF( TimeZoneSidKey='Europe/London', '+00', 
                        IIF( TimeZoneSidKey='Australia/Sydney', '+11', 
                            IIF( TimeZoneSidKey='Asia/Singapore', '+08', 
                                IIF( TimeZoneSidKey='Europe/Paris', '+01', 
                                    IIF( TimeZoneSidKey='Asia/Dubai', '+04', 
                                        IIF( TimeZoneSidKey='America/Denver', '-07', 
                                            IIF( TimeZoneSidKey='Europe/Dublin', '+00', 
                                                IIF( TimeZoneSidKey='America/Los_Angeles', '-08', '+xx' ) ) ) ) ) ) ) ) ), CONCAT( CONCAT( IIF(IsNULL(SundayStartTime),'N','Y'), IIF(IsNULL(MondayStartTime),'N','Y') ), CONCAT( IIF(IsNULL(TuesdayStartTime),'N','Y'), IIF(IsNULL(WednesdayStartTime),'N','Y') ) ) ), CONCAT( CONCAT( IIF(IsNULL(ThursdayStartTime),'N','Y'), IIF(IsNULL(FridayStartTime),'N','Y') ), CONCAT( IIF(IsNULL(SaturdayStartTime),'N','Y'), CONCAT( TO_CHAR(MondayStartTime,'HH24:MI'), TO_CHAR(MondayEndTime,'HH24:MI') ) ) ) )
		*/
        return '';
	}
    public static testmethod void testServiceContractTrigger(){
        Address__c add = [SELECT Id, Account__c FROM Address__c WHERE account__c != null and Oracle_Address_Id__c != null and active__c = true Limit 1];
        //cannot set businessHours in testcode 
        //setup BusinessHourTempStore__c 
        List<BusinessHours> bhs = [SELECT FridayStartTime,Id,IsActive,IsDefault,MondayEndTime,MondayStartTime,SaturdayStartTime,
                      SundayStartTime,ThursdayStartTime,Name,TimeZoneSidKey,TuesdayStartTime,WednesdayStartTime 
                      FROM BusinessHours WHERE IsActive = True];
        List<BusinessHourTempStore__c> bhTemps = new List<BusinessHourTempStore__c>();
        for(BusinessHours bh : bhs){
            BusinessHourTempStore__c bht = new BusinessHourTempStore__c();
            	bht.CoverageFriday__c = (bh.FridayStartTime!=null);
                bht.CoverageMonnday__c = (bh.MondayStartTime!=null);
                bht.CoverageSaturday__c = (bh.SaturdayStartTime!=null);
                bht.CoverageSunday__c = (bh.SundayStartTime!=null);
                bht.CoverageThursday__c = (bh.ThursdayStartTime!=null);
                bht.CoverageTuesday__c = (bh.TuesdayStartTime!=null);
                bht.CoverageWednesday__c = (bh.WednesdayStartTime!=null);
            	bht.EndTime__c = string.valueOf(bh.MondayEndTime);
            	bht.Integration_Id__c = null;
            	bht.IsDefault__c = bh.IsDefault;
            	bht.TimeZoneSIDKey__c = bh.TimeZoneSidKey;
                bht.Business_Hours_ID__c = bh.id;
            bhTemps.add(bht);
        }
        //setup business hours settings
        ServiceCloudSettings__c scSetting = new ServiceCloudSettings__c();
        scSetting.Name = 'DefaultBusinessHours';
        //scSetting.Value__c = bhId;
        list<ServiceContract> scs = new List<ServiceContract>();
        for(integer i = 0; i <51; i++){
            ServiceContract sc = new ServiceContract();
            	//Integer rand = Math.round(Math.random()*bhTemps.size())-1;
            	Integer rand = 0;
            	sc.Business_Hours_Integration__c = bhTemps[rand].Integration_Id__c;
            	sc.Name = 'test' + i;
                sc.AccountId = add.Account__c;
                sc.Service_Level__c = 'Standard';
                 sc.End_Customer_Account__c = add.Account__c;
                 sc.Bill_To_Account__c = add.Account__c;
                 sc.Ship_To_Account__c = add.Account__c;
                 sc.Bill_To_Address__c = add.id;
                 sc.Ship_To_Address__c = add.id;
                 sc.Oracle_Contract_Line_ID__c = 'ohid';
                 sc.Pricebook2Id = Test.getStandardPricebookId();
                 sc.Price_Book__c = Test.getStandardPricebookId();
            scs.add(sc);
        }
        insert scs;
        
    }
}