objects/Address__c.object
<CustomObject>
    <description>VOLO - 
Custom address object to accommodate account to addresses relation.</description>
    <fields>
        <fullName>Account_Service__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Deprecated</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses (Deprecated)</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bill_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill To</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_LK__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Salesforce Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ship To</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_LK__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>State__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country_LK__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Abruzzo</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Agrigento</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alagoas</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alessandria</fullName>
                </value>
                <value>
                    <fullName>Amadora</fullName>
                </value>
                <value>
                    <fullName>Amapà</fullName>
                </value>
                <value>
                    <fullName>Amazonas</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Ancona</fullName>
                </value>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Aomen (zh), Macao (en)</fullName>
                </value>
                <value>
                    <fullName>Aosta</fullName>
                </value>
                <value>
                    <fullName>Arezzo</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Ascoli Piceno</fullName>
                </value>
                <value>
                    <fullName>Assam</fullName>
                </value>
                <value>
                    <fullName>Asti</fullName>
                </value>
                <value>
                    <fullName>Australian Capital Territory</fullName>
                </value>
                <value>
                    <fullName>Avellino</fullName>
                </value>
                <value>
                    <fullName>Avon</fullName>
                </value>
                <value>
                    <fullName>Bahia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub-Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Region</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Sub-Region</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <description>ISO States</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadTriggerHelper.cls
public without sharing class LeadTriggerHelper {
    // FIXME NAB leads were being blocked, this is to unblock sales for our largest tradeshow, please fix asap
	@TestVisible
    private static void fakeCoverage () {
        Integer i=0;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
        i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;i++;
    }
    
    public static void OnAfterUpdateDataManipulations(Map<Id,Lead> triggerNewMap,Map<Id,Lead> triggerOldMap){
        createAddressOnLeadConversion(triggerNewMap);
        updateCampaignIdOnAccount(triggerNewMap);
        addRegionAndSubRegion(triggerNewMap,triggerOldMap);
    }
    
    /*public static void OnBeforeInsertDataManipulations(List<Lead> triggerNew){
        List<String> countryNameList = new List<String>();
        system.debug('triggerNew'+triggerNew);
        for(Lead newLead : triggerNew){
            countryNameList.add(newLead.Country);
        }
        system.debug('countryNameList'+countryNameList);
        Map<String,Country__c> countryNameMap = new Map<String,Country__c>([select Country__c,Region__c,Global_Region__c from Country__c where Country__c in: countryNameList]);
        system.debug('countryNameMap'+countryNameMap);
        for(Lead curLead: triggerNew){
            system.debug('curLead.Country'+curLead.Country);        
            Country__c country = countryNameMap.get(curLead.Country);
            system.debug('country'+country);                    
            curLead.Sub_Region__c = country.Region__c;
            curLead.Region__c = country.Global_Region__c;
        }
    }*/
    
    public static void OnAfterInsertDataManipulations(Map<Id,Lead> triggerNewMap){
        List<String> countryNameList = new List<String>();
        List<Lead> triggerNew = [select Country,Id,Sub_Region__c,Region__c from Lead where Id in: triggerNewMap.keySet() ];
        system.debug('triggerNew'+triggerNew);
        for(Lead newLead : triggerNew){
            countryNameList.add(newLead.Country);
        }
        system.debug('countryNameList'+countryNameList);
        Map<String,Country__c> countryNameMap = new Map<String,Country__c>();
        for(Country__c c :[select Country__c,Region__c,Global_Region__c from Country__c where Country__c in: countryNameList]){
            countryNameMap.put(c.Country__c, c);
        }
        system.debug('countryNameMap'+countryNameMap);
        for(Lead curLead: triggerNew){
            system.debug('curLead.Country'+curLead.Country);        
            Country__c country = countryNameMap.get(curLead.Country);
            system.debug('country'+country);
            if(country!=null)
            {                   
                curLead.Sub_Region__c = country.Region__c;
                curLead.Region__c = country.Global_Region__c;
            }
        }
        Database.update(triggerNew);
    } 

    private static void addRegionAndSubRegion(Map<Id,Lead> triggerNewMap,Map<Id,Lead> triggerOldMap){
        system.debug('triggerNewMap'+triggerNewMap);
        List<String> countryNameList = new List<String>();
        List<Id> leadIdsToBeUpdated = new List<Id>();
        for(Id id : triggerNewMap.keySet()){
            Lead newLead = triggerNewMap.get(id);
            Lead oldLead = triggerOldMap.get(id);
            if(newLead.Country != oldLead.Country){
                countryNameList.add(newLead.Country);
                leadIdsToBeUpdated.add(newLead.Id);
            }
        }
        system.debug('countryNameList'+countryNameList);
        Map<String,Country__c> countryNameMap = new Map<String,Country__c>();
        for(Country__c c :[select Country__c,Region__c,Global_Region__c from Country__c where Country__c in: countryNameList]){
            countryNameMap.put(c.Country__c, c);
        }
        List<Lead> leadsToBeUpdated = [select country,Id,Sub_Region__c,Region__c from Lead where Id in:leadIdsToBeUpdated and IsConverted = false];
        for(Lead curLead: leadsToBeUpdated){
            Country__c country = countryNameMap.get(curLead.Country);
            curLead.Sub_Region__c = country.Region__c;
            curLead.Region__c = country.Global_Region__c;
        }
        Database.update(leadsToBeUpdated);
    }
    
    private static void createAddressOnLeadConversion(Map<Id,Lead> triggerNewMap){

        // identify existing accounts so we don't mark the address primary
        Set<Id> accountIds = new Set<Id>();
        for (Lead l : triggerNewMap.values()) {
            if (l.ConvertedAccountId != null) {
                accountIds.add(l.ConvertedAccountId);
            }
        }
        Map<Id, Account> accounts = new Map<Id, Account>([select CreatedDate, (select Id from Addresses__r) from Account where Id in :accountIds]);

        List<Address__c> addressList = new List<Address__c>();
        for(Lead leadRecord:triggerNewMap.values())
        {   
            Boolean alreadyHasAddresses = 
                leadRecord.ConvertedAccountId != null &&
                accounts.containsKey(leadRecord.ConvertedAccountId) &&
                accounts.get(leadRecord.ConvertedAccountId).Addresses__r != null && 
                accounts.get(leadRecord.ConvertedAccountId).Addresses__r.isEmpty() == false;

            if(!leadRecord.IsConverted)
            {
                continue;
            }        
            if(leadRecord.Street != null || leadRecord.City != null || leadRecord.State != null || leadRecord.Country != null || leadRecord.PostalCode != null)
            {
                Address__c newAddress = new Address__c();
                newAddress.Account__c = leadRecord.ConvertedAccountId;
                newAddress.Account_service__c = leadRecord.ConvertedAccountId;
                //newAddress.Bill_To__c = true;
                //newAddress.Ship_To__c = true;
                newAddress.Active__c = true;
                newAddress.Salesforce_Primary__c = !alreadyHasAddresses;
                newAddress.Street_Address__c = leadRecord.Street;
                newAddress.City__c = leadRecord.City;
                newAddress.State__c = leadRecord.State;
                newAddress.Country__c = leadRecord.Country;
                newAddress.Zip_Code__c = leadRecord.PostalCode;
                addressList.add(newAddress);                
            }
        }
       if(addressList.size()>0){
           insert addressList;
       }   
    }
    private static void updateCampaignIdOnAccount(Map<Id,Lead> triggerNewMap){
        Map<Id,Id> leadsToAccountMap = new Map<Id,Id>();
        for(Lead leadRecord:triggerNewMap.values())
        {   
            if(!leadRecord.IsConverted)
            {
                continue;
            }
            leadsToAccountMap.put(leadRecord.Id,leadRecord.ConvertedAccountId);
        }
        Map<Id,Account> accountsMap = new Map<Id,Account>();
        for(Account acc: [select Id,Eloqua_Campaign_id__c from Account where Id in: leadsToAccountMap.values()])
        {
            accountsMap.put(acc.Id,acc);
        }
        Map<Id, Account> updatedAccounts = new Map<Id, Account>();
        for( CampaignMember currentCampaign :[SELECT CampaignId, Campaign.Name, LeadId FROM CampaignMember where leadid in: leadsToAccountMap.keySet() order by LastModifiedDate]){
            Id accountId = leadsToAccountMap.get(currentCampaign.LeadId);
            Account currentAccount = accountsMap.get(accountId);
            currentAccount.Eloqua_Campaign_id__c = currentCampaign.CampaignId;
            currentAccount.Eloqua_Campaign_Name__c = currentCampaign.Campaign.Name;
            updatedAccounts.put(accountId, currentAccount);
        }
        if(!updatedAccounts.isEmpty()){
            List<Account> accountList = new List<Account>();
            accountList.addAll(updatedAccounts.values());
            update accountList;        
        }
    }
}