objects/Archive_Account_History__c.object
<CustomObject>
    <description>Archived Account history changes related to Account names</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Archive Account History</relationshipLabel>
        <relationshipName>Archive_Account_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <label>New Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Old_Value__c</fullName>
        <label>Old Value</label>
        <type>TextArea</type>
    </fields>
    <label>Archive Account History</label>
    <nameField>
        <displayFormat>H-{0000000}</displayFormat>
        <label>Archive Account History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Archive Account History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchArchiveAccountHistoryTest.cls
@isTest
public class BatchArchiveAccountHistoryTest {
	@isTest
    private static void archiveAccountTest(){
        Account ac = TestDataFactory.createAccount();
        // change owner so a history is generated
        ac.OwnerId = [
            select Id 
            from User 
            where IsActive = true 
            and Profile.Name = 'System Administrator' 
            order by LastModifiedDate desc 
            limit 1
        ][0].Id;
        update ac;
        AccountHistory objectHistory = new AccountHistory(
            AccountId = ac.Id, 
            Field = 'Site'
        );
        insert objectHistory;
        test.startTest();
        BatchArchiveAccountHistory accArchiveBatch = new BatchArchiveAccountHistory();
        Database.executeBatch(accArchiveBatch, 200);
        test.stopTest();
        List<Archive_Account_History__c> archAccountHistoryList = [SELECT Account__c, Field__c FROM Archive_Account_History__c];
        system.assertEquals('Site', archAccountHistoryList[0].Field__c , 'Field is incorrect');
        system.assertEquals(ac.Id, archAccountHistoryList[0].Account__c , 'Account id is incorrect');
        system.assertEquals(1, archAccountHistoryList.size(), 'Account History record is not returned');
    }
    @isTest
    private static void scheduleBatchTimeReportingTest() {
        String CRON_EXP = '0 0 0 3 9 ? *';
		Test.startTest();
		String jobId = System.schedule('BatchArchiveAccountHistory_TEST', CRON_EXP, new BatchArchiveAccountHistory());
      	CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
      	System.assertEquals(CRON_EXP, ct.CronExpression);
      	System.assertEquals(0, ct.TimesTriggered);
		Test.stopTest();
    }
    @isTest
    private static void testErrorEmail () {
        BatchArchiveAccountHistory b = new BatchArchiveAccountHistory();
        b.upsertErrors = 'TESTING123!';
        b.finish(null);
        // TODO assert
    }
    @isTest
    private static void testNameLookup () {
        BatchArchiveAccountHistory x = new BatchArchiveAccountHistory();
        List<Archive_Account_History__c> histories = new List<Archive_Account_History__c>();
        histories.add(new Archive_Account_History__c(
        	Field__c = 'Owner',
            Old_Value__c = UserInfo.getUserId(),
            New_Value__c = UserInfo.getUserId()
        ));
        x.convertIdsToNames(histories);
		System.assertEquals(UserInfo.getUserName(), histories[0].Old_Value__c);
		System.assertEquals(UserInfo.getUserName(), histories[0].New_Value__c);
    }
}