objects/Bug__c.object
<CustomObject>
    <description>Bugs related to Service cases and integrate with the bug tracking system</description>
    <fields>
        <fullName>Bug_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this box is checked, it means that there are Bug related attachments in Chatter on the Bug record.</description>
        <inlineHelpText>When this box is checked, it means that there are Bug related attachments in Chatter on the Bug record.</inlineHelpText>
        <label>Bug Attachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Bugs</relationshipLabel>
        <relationshipName>Bugs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Developer_Comments__c</fullName>
        <label>Developer Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>For Non-Integrated bugs, enter &quot;Completed&quot; when the fix is completed</inlineHelpText>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Bug</label>
    <nameField>
        <displayFormat>Bug-{0}</displayFormat>
        <label>SF Bug Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bugs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/test_Bugs.cls
@isTest
public class test_Bugs {
    public static testmethod void testBugComments(){
        list<Case> cases = test_utility.createCases(1,true);
		bug__c bug = new bug__c();
		bug.Case__c = cases[0].Id;
		bug.Bug_Attachments__c = true;
		bug.Comments__c = 'Test';
		bug.Description__c = 'Description';
		Bug.Developer_Comments__c = 'DevComments';
        bug.Status__c = 'submitted';
		insert bug;
        bug.Comments__c = 'More Test';
        bug.Description__c = 'More Description';
        bug.Developer_Comments__c = 'More DevComments';
        update bug;
        blogic_bug.sendBug(bug.Id);
        blogic_BugRestApi.doPost();
    }
    public static testMethod void getBug() {
        blogic_BugRestApi.getBug('test');
    }
    public static testMethod void doGet() {
		RestContext.request = new RestRequest();
        
        // without bugId
        blogic_BugRestApi.doGet();
        
        // with bugId
        RestContext.request.params.put('bugId', 'test');
        blogic_BugRestApi.doGet();
    }
    public static testMethod void nnull() {
        System.assertEquals('', blogic_BugRestApi.nnull(''));
        System.assertNotEquals(null, blogic_BugRestApi.nnull(null));
    }
}