objects/Bug__c.object
<CustomObject>
    <description>Bugs related to Service cases and integrate with the bug tracking system</description>
    <fields>
        <fullName>Unique_Flow_Identifier__c</fullName>
        <description>Used in flow to determine newly created record.</description>
        <label>Unique Flow Identifier</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Bug</label>
    <nameField>
        <displayFormat>Bug-{0}</displayFormat>
        <label>SF Bug Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bugs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FlowRedirectController.cls
public with sharing class FlowRedirectController {
    
    public PageReference onLoad() {
        String unique_id = ApexPages.currentPage().getParameters().get('id');
        
        if(String.isNotBlank(unique_id))
            for (Bug__c bug : [SELECT Id FROM Bug__c WHERE Unique_Flow_Identifier__c = :unique_id order by CreatedDate desc])
                return new PageReference('/' + bug.Id);
        
        return new PageReference('/home/home.jsp'); 
        
    }

}