objects/Bug__c.object
<CustomObject>
    <description>Bugs related to Service cases and integrate with the bug tracking system</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Case__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bug_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this box is checked, it means that there are Bug related attachments in Chatter on the Bug record.</description>
        <inlineHelpText>When this box is checked, it means that there are Bug related attachments in Chatter on the Bug record.</inlineHelpText>
        <label>Bug Attachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bug_Integration_Id__c</fullName>
        <description>The Correlation Id received from a successful bug submission.</description>
        <label>Bug Integration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bug_Number__c</fullName>
        <label>Bug Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bugzilla_URL__c</fullName>
        <label>Bug URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Asset_Version__c</fullName>
        <formula>IF(ISBLANK(Case__r.Reported_Version__c), Case__r.Asset.Version__c,Case__r.Reported_Version__c)</formula>
        <label>Case Asset Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Priority__c</fullName>
        <formula>TEXT(Case__r.Priority)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Priority</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Product_Category__c</fullName>
        <formula>Case__r.Product_Class_Category__r.Name</formula>
        <label>Case Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Product_Family__c</fullName>
        <formula>Case__r.Product_Class__r.Service_Product_Family__c</formula>
        <label>Case Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Severity__c</fullName>
        <formula>TEXT(  Case__r.Severity__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Severity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Bugs</relationshipLabel>
        <relationshipName>Bugs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Developer_Comments__c</fullName>
        <label>Developer Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fixed_Version_Number__c</fullName>
        <inlineHelpText>= Implemented Version in Jira</inlineHelpText>
        <label>Fixed Version Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Bug_Number__c</fullName>
        <description>This field shows the original Bug Number if the developers realized it was a duplicate and changed the Bug Number to an alternate value.</description>
        <inlineHelpText>This field shows the original Bug Number if the developers realized it was a duplicate and changed the Bug Number to an alternate value.</inlineHelpText>
        <label>Old Bug Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation_Code__c</fullName>
        <label>Operation Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Customer_Number__c</fullName>
        <formula>Case__r.Oracle_Customer_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Oracle Customer Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planned_Completion__c</fullName>
        <label>Planned Completion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_Date__c</fullName>
        <label>Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Siebel_Row_Id__c</fullName>
        <externalId>true</externalId>
        <label>Siebel Row Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>For Non-Integrated bugs, enter &quot;Completed&quot; when the fix is completed</inlineHelpText>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the user that completed the submission of the bug to the bug system.</description>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bugs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted to Dev - Enhance</fullName>
                </value>
                <value>
                    <fullName>Submitted to Dev - Bug</fullName>
                </value>
                <value>
                    <fullName>Submitted to Dev - Support</fullName>
                </value>
                <value>
                    <fullName>Submitted to Dev - Work Item</fullName>
                </value>
                <value>
                    <fullName>Submitted to Dev - Work Order</fullName>
                </value>
                <value>
                    <fullName>Updated by Development</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Update_Date__c</fullName>
        <label>Update Date</label>
        <type>Date</type>
    </fields>
    <label>Bug</label>
    <nameField>
        <displayFormat>Bug-{0}</displayFormat>
        <label>SF Bug Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bugs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceCloudSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Administrative settings for the service cloud deployment</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ServiceCloudSettings</label>
</CustomObject>

classes/blogic_Bug.cls
global without sharing class blogic_Bug {
    global static void updateDevComment(Map<Id,Bug__c> oldBugs,Map<Id,Bug__c> newBugs){
        system.debug('oldBugs is : '+oldBugs);
        system.debug('newBugs is : '+newBugs);
        
        List<Bug__c> changedBugs = new List<Bug__c>();
        
        //Looping through the values to check if the comments have changed from Bugzilla
        for(Bug__c b : newBugs.values()){
            if(b.Developer_Comments__c != oldBugs.get(b.Id).Developer_Comments__c && (b.Developer_Comments__c != null || oldBugs.get(b.Id).Developer_Comments__c != null)){
                    changedBugs.add(b);
            }
            //check to make sure the status will not be overwritten by "submitted"
            if(b.status__c != null && b.status__c.toLowerCase() == 'submitted'){
               if(!String.IsEmpty(oldBugs.get(b.id).status__c)){
                   b.status__c = oldBugs.get(b.id).status__c;
               }
            }
        }
        system.debug('changedBugs is : '+changedBugs);
        if(changedBugs == null){
            return;
        }
        //Looping through the bugs that has new comments to append
        for(Bug__c bug : changedBugs){
            String oldValue = oldBugs.get(bug.Id).Developer_Comments__c;
            String newValue = newBugs.get(bug.Id).Developer_Comments__c;
            
            if(oldValue != null && newValue != null){
                newBugs.get(bug.Id).Developer_Comments__c = oldValue +'\n'+system.now()+'\n'+ newValue;    
            }else if(oldValue != null && newValue == null){
                newBugs.get(bug.Id).Developer_Comments__c = oldValue;
            }else if(oldValue == null && newValue != null){
                newBugs.get(bug.Id).Developer_Comments__c = newValue;
            }
            
        }
        system.debug('newBugs is : '+newBugs);
        
    }
    
    global static string nnull(String val){
        if(val==null)
            val = '';
        return val.escapeXml();
    }
    
    webservice static string sendBug(Id bugId){
        String result = '';
        try{
            if(bugId!=null){
                
                Bug__c bug = [SELECT Account_Name__c,case__r.CaseNumber, Bugzilla_URL__c,Bug_Attachments__c,Bug_Number__c,Case_Asset_Version__c,Bug_Integration_Id__c,
                              Case_Priority__c,Case_Product_Category__c,Case_Product_Family__c,Case_Severity__c,Case__c,
                              Comments__c,CreatedBy.Name,CreatedDate,CurrencyIsoCode,Description__c,Developer_Comments__c,
                              Fixed_Version_Number__c,Id,IsDeleted,LastModifiedById,LastModifiedDate,
                              Name,Old_Bug_Number__c,Operation_Code__c,Oracle_Customer_Number__c,
                              Planned_Completion__c,RecordTypeId,Record_Type__c,Release_Date__c,Siebel_Row_Id__c,Status__c,
                              Submitted_By__c,Submitted_Date__c,SystemModstamp,Type__c,Update_Date__c FROM Bug__c WHERE Id = :bugId];
                
                String response = bugCallOut(getXMLOut(bug));
                if(!response.contains('Error')){
                    bug.Bug_Integration_Id__c = response;
                    update bug;
                    result = 'Success.';
                } else {
                    result = response;
                }
            }
        }
        catch(exception e){
            result = e.getMessage();
        }
        return result;
    }
    
    global static string getXMLOut(bug__c bug){
        String response = '';
        if(bug!=null){

            list<StaticResource> srs = [SELECT Id,Name,body FROM StaticResource WHERE Name = 'BugOutxml'];
            
            if(srs.size()>0){
                String ns = 'http://www.siebel.com/xml/H_BCDActivityBugzillaInterfaceOB';
                Dom.Document xdoc = new Dom.Document();
                xdoc.load(srs[0].body.tostring());
                
                //Retrieve the root element for this document.
                Dom.XMLNode bugMessageDoc = xdoc.getRootElement();
                Dom.XMLNode bugMessageList = bugMessageDoc.getChildElement('ListOfH_BcdActivityBugzillaInterfaceOb',ns);
                Dom.XMLNode bugMessage = bugMessageList.getChildElement('H_BcdActivityBugzillaInterface',ns);
                system.debug('message ' + bugMessage);
                bugMessage.getChildElement('AccountId', ns).addTextNode(nnull(bug.Oracle_Customer_Number__c));
                bugMessage.getChildElement('AccountName', ns).addTextNode(nnull(bug.Account_Name__c));
                bugMessage.getChildElement('ActivityId', ns).addTextNode(bug.Id);
                bugMessage.getChildElement('ActivityUpdateDateTime', ns).addTextNode(string.valueOf(bug.LastModifiedDate));
                bugMessage.getChildElement('Attachment', ns).addTextNode(nnull(string.valueOf(bug.Bug_Attachments__c)));
                bugMessage.getChildElement('BugId', ns).addTextNode(nnull(bug.Bug_Number__c));
                bugMessage.getChildElement('BugURL', ns).addTextNode(nnull(bug.Bugzilla_URL__c));
                bugMessage.getChildElement('BugUpdDt', ns).addTextNode(nnull(string.valueOf(bug.Update_Date__c)));
                bugMessage.getChildElement('Comments', ns).addTextNode(nnull(bug.Developer_Comments__c));
                bugMessage.getChildElement('Component', ns).addTextNode(nnull(bug.Case_Product_Category__c));
                bugMessage.getChildElement('CreatedByName', ns).addTextNode(bug.CreatedBy.Name);
                bugMessage.getChildElement('CritDateTime', ns).addTextNode(nnull(string.valueOf(bug.Planned_Completion__c)));
                bugMessage.getChildElement('DeadlineDateTime', ns).addTextNode(nnull(string.valueOf(bug.Release_Date__c)));
                bugMessage.getChildElement('Description', ns).addTextNode(nnull(bug.Comments__c));
                bugMessage.getChildElement('FixedVerNum', ns).addTextNode(nnull(bug.Fixed_Version_Number__c));
                bugMessage.getChildElement('OldBugNum', ns).addTextNode(nnull(bug.Old_Bug_Number__c));
                bugMessage.getChildElement('OperationCode', ns).addTextNode(nnull(bug.Operation_Code__c));
                bugMessage.getChildElement('Priority', ns).addTextNode(nnull(bug.Case_Priority__c));
                
                bugMessage.getChildElement('Product', ns).addTextNode(nnull(bug.Case_Product_Family__c));
                //system.debug('family: ' + bugMessage.getChildElement('Product', ns).getText());
                bugMessage.getChildElement('ServiceRequestId', ns).addTextNode(bug.case__r.CaseNumber);
                bugMessage.getChildElement('Severity', ns).addTextNode(nnull(bug.Case_Severity__c));
                bugMessage.getChildElement('Status', ns).addTextNode(nnull(bug.Status__c));
                bugMessage.getChildElement('Summary', ns).addTextNode(nnull(bug.Description__c));
                bugMessage.getChildElement('Type', ns).addTextNode(nnull(bug.Type__c));
                bugMessage.getChildElement('VerNum', ns).addTextNode(nnull(bug.Case_Asset_Version__c));
                
                response = xdoc.toXmlString().replace('&amp;amp;','&amp;' );
                
            }
        }
        return response;
    }
    
    global static string bugCallOut(String bugXml){
        String response = '';
        try{
            //this is the test callout check custom setting for prod
            String url = 'http://66.70.8.153/Bugzilla/BTSHTTPReceive.dll';
            try{
                ServiceCloudSettings__c bhs = ServiceCloudSettings__c.getValues('BugUrl');
                url = bhs.value__c;
            } catch (exception e){
                //trap custom setting exception
                system.debug('=================================================');
                system.debug('  Custom Setting BugUrl Is Not Set');
                system.debug('=================================================');
            }
            
            
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint(url);
            req.setMethod('POST');
            req.setBody(bugXml);
            if(test.isRunningTest()){
                response = '<BizTalkHttpReceive><CorrelationToken TokenType="SUBMIT">{VALUE}</CorrelationToken></BizTalkHttpReceive>';
            } else {
                HttpResponse res = h.send(req);
                response = res.getBody();
            } 
        } catch(exception e){
            response = e.getMessage();
        }
        if(response!=null && response.contains('<BizTalkHttpReceive><CorrelationToken TokenType="SUBMIT">{')){
            response = response.remove('<BizTalkHttpReceive><CorrelationToken TokenType="SUBMIT">{');
            response = response.remove('}</CorrelationToken></BizTalkHttpReceive>');
        }   else {
            if(response == null)
                response = 'Null http response.';
            response = 'Error: ' + response;
        }
        return response;
    }
    
}