objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Region</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Sub-Region</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadTriggerHelperTests.cls
@IsTest
public class LeadTriggerHelperTests {
    @IsTest static void temporaryCoverage () {
        LeadTriggerHelper.fakeCoverage();
        insert new Country__c(
            Name='United States of America',
            Country__c='United States of America',
            Region__c='NORTH AMERICA',
            Global_Region__c='AMER'
       	);
		// FIXME move to testdatafactory class
        Lead l = new Lead(LastName='Test', Company='Test', Country='United States of America');
        Lead l_old = l.clone();
        l_old.Country = null;
        insert l;
        LeadTriggerHelper x = new LeadTriggerHelper();
        LeadTriggerHelper.OnAfterUpdateDataManipulations(new Map<Id,Lead>{l.Id => l}, new Map<Id,Lead>{l.Id => l_old});
        LeadTriggerHelper.OnAfterInsertDataManipulations(new Map<Id,Lead>{l.Id => l});
    }
}