objects/Customer_Commitments__c.object
<CustomObject>
    <fields>
        <fullName>Jira_Sync__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Jira Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Commitments</relationshipLabel>
        <relationshipName>Customer_Commitments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Commitment</label>
    <nameField>
        <label>Commitment Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Commitments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Line Items</relationshipLabel>
        <relationshipName>Opportunity_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>oli-{0000}</displayFormat>
        <label>Opportunity Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/test_CustomerCommits.cls
@isTest
public class test_CustomerCommits {
    
    public static testmethod void testCommits(){
        
        Account a = TestDataFactory.createAccount();
        Opportunity o = TestDataFactory.createOpportunity(a);
		
        // TODO move to TestDataFactory
        Customer_Commitments__c cc = new Customer_Commitments__c();
        cc.Opportunity__c = o.Id;
        insert cc;
		
        Test.startTest();
        
        cc.Jira_Sync__c = true;
        update cc;
        
        Test.stopTest();
        
        // TODO assert something
    }
    
}