objects/Integration_Log__c.object
<CustomObject>
    <description>This object tracks and records the integration processing. Errors and response messages are logged to this object by Informatica.</description>
    <fields>
        <fullName>DeleteDate__c</fullName>
        <formula>DATEVALUE( CreatedDate ) +  IF(ISNULL(Days_to_Keep__c),30,Days_to_Keep__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DeleteDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsResolved__c</fullName>
        <formula>NOT(ISNULL( Resolved_DateTime__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsResolved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requires_Attention__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not this log item requires manual intervention to resolve.</description>
        <inlineHelpText>Indicates whether or not this log item requires manual intervention to resolve.</inlineHelpText>
        <label>Requires Attention</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>Integration Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/test_IntegrationLogsClean.cls
@isTest
global class test_IntegrationLogsClean {
    
    global static testMethod void testCleanLogs(){
        
        //create logs that would persist for 30 days
        for(integer i=0;i<100;i++){
            blogic_IntegrationLog.createErrorLog('ActionTest','MessageTest','DetailTest');
        }
        blogic_IntegrationLog.doInsertLogs();
        //create logs that should be deleted
        for(integer i=0;i<250;i++){
            blogic_integrationLog.createLog('Category', 'Direction', 'Action', 'Message', 
                                            'Detail', 'ObjectAPI', 'ObjectId', 'ExternalSystem', 
                                            'ExternalId', 'BatchId', -2, false);
        }
        test.startTest();
        schedule_IntegrationLog.startbatch();
        test.stopTest();

        list<Integration_Log__c> ilds = [SELECT Id FROM Integration_Log__c 
                                         WHERE DeleteDate__c < TODAY 
                                         AND (IsResolved__c = true or Requires_Attention__c = false)];
        system.assertEquals(0, ilds.size());

        
        
    }
    
    
}