objects/Integration_Log__c.object
<CustomObject>
    <description>This object tracks and records the integration processing. Errors and response messages are logged to this object by Informatica.</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submission</fullName>
                </value>
                <value>
                    <fullName>Response</fullName>
                </value>
                <value>
                    <fullName>Synchronization</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <description>The Batch process this action is a part of, if relevant.</description>
        <inlineHelpText>The Batch process this action is a part of, if relevant.</inlineHelpText>
        <label>Batch Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>The category of the log.</description>
        <inlineHelpText>The category of log.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integration</fullName>
                    <default>true</default>
                    <label>Integration</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Days_to_Keep__c</fullName>
        <defaultValue>30</defaultValue>
        <description>Number of days to keep this record active in Salesforce. After this number of days, if the record is not marked Requires Attention, or is marked IsResolved, the record will be deleted.</description>
        <inlineHelpText>Number of days to keep this record active in Salesforce.</inlineHelpText>
        <label>Days to Keep</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DeleteDate__c</fullName>
        <formula>DATEVALUE( CreatedDate ) +  IF(ISNULL(Days_to_Keep__c),30,Days_to_Keep__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DeleteDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OutFromSF</fullName>
                </value>
                <value>
                    <fullName>InToSF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>The Id from the External System for the object this action is working against, if relevant.</description>
        <inlineHelpText>The Id from the External System for the object this action is working against, if relevant.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System__c</fullName>
        <description>The external system relevant to this action.</description>
        <inlineHelpText>The external system relevant to this action.</inlineHelpText>
        <label>External System</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsResolved__c</fullName>
        <formula>NOT(ISNULL( Resolved_DateTime__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsResolved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Object_Api_Name__c</fullName>
        <description>The API name of the primary object this action works against, if relevant.</description>
        <inlineHelpText>The API name of the primary object this action works against, if relevant.</inlineHelpText>
        <label>Object Api Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>Salesforce Id of the object this action works against, if relevant.</description>
        <inlineHelpText>Salesforce Id of the object this action works against, if relevant.</inlineHelpText>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Attention__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not this log item requires manual intervention to resolve.</description>
        <inlineHelpText>Indicates whether or not this log item requires manual intervention to resolve.</inlineHelpText>
        <label>Requires Attention</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>Integration Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/blogic_IntegrationLog.cls
global without sharing class blogic_IntegrationLog implements Database.Batchable<sObject>{
	
    global static list<Integration_Log__c> insertLogs {get;set;}
    global static set<Id> currentIdSet {get;set;}
    
    global Database.queryLocator start(Database.BatchableContext bc){
        String query = '';
        if(test.isRunningTest()){
            query = 'Select id from Integration_Log__c limit 200';
        }
        else{
            query = 'SELECT Id FROM Integration_Log__c WHERE ((DeleteDate__c < TODAY AND (IsResolved__c = true or Requires_Attention__c = false)) OR (DeleteDate__c < LAST_N_DAYS:15)) LIMIT 50000';
        }
         return Database.getQueryLocator(query); 
      }
    
    global void execute(Database.BatchableContext BC, List<Integration_Log__c> scope){
        system.debug('==================================================');
        try{
            List<Database.DeleteResult> drs = database.delete(scope,false);
            system.debug('  cleanLogs deleteResult size: ' + drs.size());
            integer i = 0;
            for(Database.DeleteResult dr : drs){
                if(!dr.isSuccess()){
                    system.debug('******************************************************************');
                    system.debug('  Delete Integration Log Error');
                    system.debug('  ID: ' + scope[i].Id);
                    // Operation failed, so get all errors                
                    for(Database.Error err : dr.getErrors()) {   
                        System.debug('    Error Code: ' + err.getStatusCode());
                        System.debug('    Message: ' + err.getMessage());
                        System.debug('    Fields that affected this error: ' + err.getFields());
                    }
                    system.debug('******************************************************************');
                }
                i++;
            }
        } catch (exception e){
            system.debug('******************************************************************');
            system.debug('  Clean Log Exception: ' + e.getMessage());
            system.debug('  Clean Log Stack Trace: ' + e.getStackTraceString());
            system.debug('******************************************************************');
        } finally {
            system.debug('==================================================');
        }
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
    //create an Integration Log of Category type error with requires Attention set to true
    global static void createErrorLog(string Action, string Message, string Detail){
        createErrorLog(Action, Message, Detail, Null, Null);
    }
    
    //create an Integration Log of Category type error with requires Attention set to true
    global static void createErrorLog(string Action, string Message, string Detail, 
                                      string ObjectAPI, string ObjectId){
        createLog('Error', null,
                  Action, Message, Detail,
                  ObjectAPI, ObjectId,
                  Null,Null,
                  Null,Null,
                 true);
    }
    
    //create an Integration Log of Category type Integration from SF to Oracle
    global static void createToOracleLog(string Action, string Message, string Detail, 
                                         string ObjectAPI, string ObjectId,
                                         string OracleID, string BatchID, boolean RequiresAttention){
        createLog('Integration', 'OutFromSF',
                  Action, Message, Detail,
                  ObjectAPI, ObjectId,
                  'Oracle',Null,
                  BatchId,Null,
                  RequiresAttention);
    }
    
    //create an Integration Log of Category type Integration from Oracle to SF
    global static void createFromOracleLog(string Action, string Message, string Detail, 
                                      	   string ObjectAPI, string ObjectId,
                                           string OracleId, string BatchID, boolean RequiresAttention){
        createLog('Integration', 'InToSF',
                  Action, Message, Detail,
                  ObjectAPI, ObjectId,
                  'Oracle',Null,
                  BatchId,Null,
                  RequiresAttention);
    }
    
    global static void createLog(string Category, string Direction, 
                                 string Action, string Message, string Detail, 
                                 string ObjectAPI, string ObjectId,
                                 string ExternalSystem, string ExternalId,
                                 string BatchId, integer DaysToKeep, 
                                 boolean RequiresAttention){       
        if(insertLogs==null)
            insertLogs = new List<Integration_Log__c>();
       
        try{
        	Integration_Log__c il = new Integration_Log__c();
        	il.Category__c = Category;
            il.Direction__c = Direction;
            
            il.Action__c = Action;
            if(String.isBlank(Message))
            	Message = 'No Message supplied';
        	il.Message__c = Message;
        	il.Detail__c = Detail;
                                     
        	il.Object_Api_Name__c = ObjectApi;
        	il.Object_Id__c = ObjectId;
                                     
            il.External_System__c = ExternalSystem;
            il.External_Id__c = ExternalId;
                                     
            il.Batch_Id__c = BatchId;
            if(DaysToKeep!=null)
            	il.Days_to_Keep__c = DaysToKeep;
            
            if(RequiresAttention==null)
                	RequiresAttention = false;
            il.Requires_Attention__c = RequiresAttention;
        	insertLogs.add(il);
        } catch (exception e){
            system.debug('******************************************************************');
            system.debug('  createLog error: ' + e.getMessage() );
            system.debug('  createLog stack: ' + e.getStackTraceString() );
            system.debug('******************************************************************');
        }
    }
    
    global static void doInsertLogs(){
        system.debug('==================================================');
        system.debug('  doInsertLogs InsertLogs Size: ' + insertLogs.size());
        system.debug('  insertLogs: ' + insertLogs);
        system.debug('==================================================');
        If(insertLogs!=null && insertLogs.size()>0){
            try{
                List<Database.SaveResult> srs = database.insert(insertLogs, false);
                integer i = 0;
                for(Database.SaveResult sr : srs){
                    if(!sr.isSuccess()){
                        system.debug('******************************************************************');
                        system.debug('  Create Integration Log Error');
                        system.debug('  Integration Log: ' + insertLogs[i]);
                        // Operation failed, so get all errors    
                        // we can't write errors here to the log object because that might cause recursion             
                        for(Database.Error err : sr.getErrors()) {   
                            System.debug('    Error Code: ' + err.getStatusCode());
                            System.debug('    Message: ' + err.getMessage());
                            System.debug('    Fields that affected this error: ' + err.getFields());
                        }
                        system.debug('******************************************************************');
                    }
                    i++;
                }
                insertLogs.clear();
            } catch (exception e){
                //we can't write errors here to the log object because that might cause recursion 
                system.debug('******************************************************************');
                system.debug('  Insert Log Exception: ' + e.getMessage());
                system.debug('  Insert Log Stack Trace: ' + e.getStackTraceString());
                system.debug('******************************************************************');
            }
        }
    }
}