objects/Milestone1_Time__c.object
<CustomObject>
    <description>This object is a replica of the Time object(Miilestone1 Unmanaged package)</description>
    <fields>
        <fullName>Hours__c</fullName>
        <inlineHelpText>The number of hours charged. Note: This cannot be more than 1 day (24 hours).</inlineHelpText>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time</label>
    <nameField>
        <label>Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseTimeEntryController_Tests.cls
@IsTest(SeeAllData=false)
private class CaseTimeEntryController_Tests {
    @IsTest
    static void shouldSaveTime(){
        Case newCase = new Case();
        newCase.Subject = 'Test case';
        newCase.SuppliedEmail = 'john.smith@gmail.com';
        insert newCase;
        
        ApexPages.StandardController stdCon = new ApexPages.StandardController(newCase);
        CaseTimeEntryController con = new CaseTimeEntryController(stdCon);
        con.timeEntry.Hours__c = 1;
        con.minutes = 40;
        con.save();
        
        List<Milestone1_Time__c> timeEntries = [select Id, Hours__c from Milestone1_Time__c];
        System.assert(timeEntries.size() == 1);
    }
}