objects/Milestone1_Time__c.object
<CustomObject>
    <description>This object is a replica of the Time object(Miilestone1 Unmanaged package)</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charge_Code__c</fullName>
        <label>Charge Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Internal Project</fullName>
                </value>
                <value>
                    <fullName>Leave of Absence</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paid Time Off (PTO)</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date the time was incurred. Defaults to today if left blank.</inlineHelpText>
        <label>Date Incurred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A description about the time. For example, why the time was incurred.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <inlineHelpText>The number of hours charged. Note: This cannot be more than 1 day (24 hours).</inlineHelpText>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incurred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user who incurred the time being charged. Defaults to current user if left blank.</inlineHelpText>
        <label>Service Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_TimesIncurred</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>TimeEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Type__c</fullName>
        <label>Time Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time</label>
    <nameField>
        <label>Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Line Items</relationshipLabel>
        <relationshipName>Opportunity_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Line Item</label>
    <nameField>
        <displayFormat>oli-{0000}</displayFormat>
        <label>Opportunity Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Reporting__c.object
<CustomObject>
    <description>Time Reporting</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Time Reporting</relationshipLabel>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charge_Code__c</fullName>
        <label>Charge Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Internal Project</fullName>
                </value>
                <value>
                    <fullName>Leave of Absence</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paid Time Off (PTO)</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Incurred__c</fullName>
        <label>Date Incurred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incurred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incurred By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MS_Time4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MS Time4</label>
        <referenceTo>Milestone1_Time__c</referenceTo>
        <relationshipLabel>Time Reporting (MS Time4)</relationshipLabel>
        <relationshipName>Time_Reporting1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Time Reporting</relationshipLabel>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MPM4_BASE__Milestone1_Project__c</referenceTo>
        <relationshipLabel>Time Reporting</relationshipLabel>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Id__c</fullName>
        <externalId>true</externalId>
        <label>Time Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Source__c</fullName>
        <label>Time Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Type__c</fullName>
        <label>Time Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Reporting</label>
    <nameField>
        <label>Time Reporting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchTimeReportingMSTime.cls
global class BatchTimeReportingMSTime implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    public String upsertErrors = '';
    public Integer batchSize = 200;
    public Datetime asOf = Datetime.now().addHours(-24);
    
    /** 
     * @description Schedulable interface entrypoint
     */
    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, this.batchSize);
    }
    
    /**
     * @description query for records which are not yet in the time reporting table or are out of date
     */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // TODO switch to formula to detect what field changes are important
        // Id NOT IN (select MS_Time2__c from Time_Reporting__c)
         return Database.getQueryLocator([
            SELECT Id, Name, Billable__c, Case__c, Category__c, Charge_Code__c, Date__c, 
            Description__c, Hours__c, Incurred_By__c, Opportunity__c, Time_Type__c,
            Case__r.Project__c
            FROM Milestone1_Time__c
            WHERE LastModifiedDate >= :asOf
            OR SystemModstamp >= :asOf
            
        ]);
        
    }
    
    /**
     * @description upsert a copy of the record into time reporting
     */
    global void execute(Database.BatchableContext bc, List<Milestone1_Time__c> msTimeList) {
      List<Time_Reporting__c> timeReportingList = new List<Time_Reporting__c>();
        for(Milestone1_Time__c mst : msTimeList) {
            Time_Reporting__c timeReporting = new Time_Reporting__c();
            timeReporting.MS_Time4__c = mst.Id;
            timeReporting.Time_Id__c = mst.Id;
            timeReporting.Name = mst.Name;
            timeReporting.Billable__c = mst.Billable__c;
            timeReporting.Category__c = mst.Category__c;
            timeReporting.Charge_Code__c = mst.Charge_Code__c;
            timeReporting.Date_Incurred__c = mst.Date__c;
            timeReporting.Description__c = mst.Description__c;
            timeReporting.Hours__c = mst.Hours__c;
            timeReporting.Incurred_By__c = mst.Incurred_By__c;
            timeReporting.Time_Type__c = mst.Time_Type__c;
            if(mst.Case__c != NULL) {
                timeReporting.Case__c = mst.Case__c;
                timeReporting.Time_Source__c = 'Case';
                // copy project (new obj) from case if populated
                if (mst.Case__r.Project__c != null)
                    timeReporting.Project__c = mst.Case__r.Project__c;
            } 
            if(mst.Opportunity__c != NULL) {
                timeReporting.Opportunity__c = mst.Opportunity__c;
                timeReporting.Time_Source__c = 'Opportunity';
            }
            timeReportingList.add(timeReporting);
        }
        Database.UpsertResult[] srList = Database.upsert(timeReportingList, Time_Reporting__c.Fields.Time_Id__c, false);
        handleErrors(srList, timeReportingList);
    }
    
    global void finish(Database.BatchableContext bc){
        
        deleteOrphaned();
        
        // don't email if no errors
        if(String.isBlank(upsertErrors)) {
            return;
        }
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage() ;
        String[] toAddresses = new String[] {'jsullivan+imagine@cloudanswers.com'};
        // TODO add person who scheduled the batch?
        mail.setToAddresses(toAddresses);
        mail.setSubject('MSTime to Time Reporting Errors');
        String body = 'Errors:\n\n' + upsertErrors;
        mail.setPlainTextBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    /**
     * @description deleted records once linked to this object 
     */
     private void deleteOrphaned () {   
        String idLike = Milestone1_Time__c.sobjecttype.getDescribe().getKeyPrefix() + '%';
        List<Time_Reporting__c> toDelete = [
            select Id 
            from Time_Reporting__c
            where Time_Id__c like :idLike
            and MS_Time4__c not in (select Id from Milestone1_Time__c)
            limit :this.batchSize
        ];
        handleErrors(Database.delete(toDelete, false), toDelete);
    }
    
    /**
     * @description finds errors in dml results and appends them to an error email body
     * @param dmlResultList the resulting list of objects to process
     * @param records the records that were sent to the dml call
     */
    private void handleErrors (List<Object> dmlResultList, List<SObject> records) {
        System.assertEquals(dmlResultList.size(), records.size(), 'different counts on records and dml results');
        for (Integer i=0; i < dmlResultList.size(); i++) {
            SObject sobj = records[i];
            List<Database.Error> errors = new List<Database.Error>();
            Database.UpsertResult ur = dmlResultList[i] instanceOf Database.UpsertResult ? (Database.UpsertResult)dmlResultList[i] : null;
            if (ur != null) errors.addAll(ur.getErrors());
            Database.DeleteResult dr = dmlResultList[i] instanceOf Database.DeleteResult ? (Database.DeleteResult)dmlResultList[i] : null;
            if (dr != null) errors.addAll(dr.getErrors());
            for(Database.Error e : errors) {
                upsertErrors += '[' + sobj.Id + '] ' + e + '\n';
                // upsertErrors += sobj + '\n';
            }
        }
    }
    
}