objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>This object is a replica of the Old Milestone object(Miilestone1 Unmanaged package)</description>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Project_Milestones2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Old Milestone</label>
    <nameField>
        <label>Old Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Old Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Milestone1_Project__c.object
<CustomObject>
    <description>This object is a replica of the Old Project object(Miilestone1 Unmanaged package)</description>
    <label>Old Project</label>
    <nameField>
        <label>Old Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Old Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Milestone1_Task__c.object
<CustomObject>
    <description>This object is a replica of the Old MS Task object(Miilestone1 Unmanaged package)</description>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipName>Project_Tasks2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <inlineHelpText>Is this task billable?</inlineHelpText>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billable</fullName>
                    <default>true</default>
                    <label>Billable</label>
                </value>
                <value>
                    <fullName>Non-Billable</fullName>
                </value>
                <value>
                    <fullName>Free</fullName>
                </value>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Support Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Old MS Task</label>
    <nameField>
        <label>Old MS Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Old MS Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Milestone1_Time__c.object
<CustomObject>
    <description>This object is a replica of the Time object(Miilestone1 Unmanaged package)</description>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date the time was incurred. Defaults to today if left blank.</inlineHelpText>
        <label>Date Incurred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <inlineHelpText>The number of hours charged. Note: This cannot be more than 1 day (24 hours).</inlineHelpText>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Task2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Task2</label>
        <referenceTo>Milestone1_Task__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <label>Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TimeViewTest.cls
@isTest
public with sharing class TimeViewTest {  
    public static TestMethod void timeViewTest(){
      Milestone1_Project__c tempproject = new Milestone1_Project__c();
      tempproject.Name = 'Temp';
      insert tempproject;
      Milestone1_Milestone__c tempmilestone = new Milestone1_Milestone__c();
      tempmilestone.Project__c = tempproject.Id;
      insert tempmilestone;
      Milestone1_Task__c temptask = new Milestone1_Task__c();
      temptask.Project_Milestone__c = tempmilestone.Id;
      insert temptask;
      Milestone1_Time__c temp = new Milestone1_Time__c();
      temp.Project_Task2__c = temptask.Id;
      temp.Date__c = Date.today();
      insert temp;
      WeeklyTimecards timeCards = new WeeklyTimecards();
      timeCards.WeekStartDate = Date.today();
      WeeklyTimecards.Timecard c = timeCards.getNewTimecard();
      c.SelectedTask = temp.Project_Task2__c;
      System.debug(c);
      c.getTotalHours();
      c.getMileStones();
      c.getTasks();
      timeCards.DoLoad();
      timeCards.SelectedIndex = 0;
      timeCards.getNewTimecard();
      System.debug(c);
      System.assertEquals(Null ,timeCards.DoNothing());
      System.assertEquals(Null ,timeCards.DoAddRow());
      System.assertEquals(Null ,timeCards.DoCancel());
      System.assertEquals(Null ,timeCards.DoPreviousWeek());
      System.assertEquals(Null ,timeCards.DoNextWeek());
      System.assertEquals(Null ,timeCards.DoDelete());
      System.assertEquals(Null ,timeCards.DoSave());
      System.debug(c);
   }
 public static TestMethod void timeViewTest2(){
      Milestone1_Project__c tempproject = new Milestone1_Project__c();
      tempproject.Name = 'Temp';
      insert tempproject;
      Milestone1_Milestone__c tempmilestone = new Milestone1_Milestone__c();
      tempmilestone.Project__c = tempproject.Id;
      insert tempmilestone;
      Milestone1_Task__c temptask = new Milestone1_Task__c();
      temptask.Project_Milestone__c = tempmilestone.Id;
      insert temptask;
      Milestone1_Time__c temp = new Milestone1_Time__c();
      temp.Project_Task2__c = temptask.Id;
      temp.Date__c = Date.today().addDays(1);
//      temp.WeekStartDate = Date.today();
      insert temp;
      WeeklyTimecards timeCards = new WeeklyTimecards();
      timeCards.WeekStartDate = Date.today();
      WeeklyTimecards.Timecard c = timeCards.getNewTimecard();
      c.SelectedTask = temp.Project_Task2__c;
      System.debug(c);
      c.getTotalHours();
      c.getMileStones();
      c.getTasks();
      timeCards.DoLoad();
      timeCards.SelectedIndex = 0;
      timeCards.getNewTimecard();
      System.assertEquals(Null ,timeCards.DoNothing());
      System.assertEquals(Null ,timeCards.DoAddRow());
      System.assertEquals(Null ,timeCards.DoCancel());
      System.assertEquals(Null ,timeCards.DoPreviousWeek());
      System.assertEquals(Null ,timeCards.DoNextWeek());
      System.assertEquals(Null ,timeCards.DoDelete());
      System.assertEquals(Null ,timeCards.DoSave());
   }
    public static TestMethod void timeViewTest3(){
      Milestone1_Project__c tempproject = new Milestone1_Project__c();
      tempproject.Name = 'Temp';
      insert tempproject;
      Milestone1_Milestone__c tempmilestone = new Milestone1_Milestone__c();
      tempmilestone.Project__c = tempproject.Id;
      insert tempmilestone;
      Milestone1_Task__c temptask = new Milestone1_Task__c();
      temptask.Project_Milestone__c = tempmilestone.Id;
      insert temptask;
      System.assertEquals(tempmilestone.Id, temptask.Project_Milestone__c);
      Milestone1_Time__c temp = new Milestone1_Time__c();
      temp.Project_Task2__c = temptask.Id;
      temp.Date__c = Date.today().addDays(2);
      insert temp;
      System.assertEquals(temptask.Id, temp.Project_Task2__c);
      WeeklyTimecards timeCards = new WeeklyTimecards();
      timeCards.WeekStartDate = Date.today();
      WeeklyTimecards.Timecard c = timeCards.getNewTimecard();
      c.SelectedTask = temp.Project_Task2__c;
      System.debug(c);
      c.getTotalHours();
      c.getMileStones();
      c.getTasks();
      timeCards.DoLoad();
      timeCards.SelectedIndex = 0;
      timeCards.getNewTimecard();
      System.assertEquals(Null ,timeCards.DoNothing());
      System.assertEquals(Null ,timeCards.DoAddRow());
      System.assertEquals(Null ,timeCards.DoCancel());
      System.assertEquals(Null ,timeCards.DoPreviousWeek());
      System.assertEquals(Null ,timeCards.DoNextWeek());
      System.assertEquals(Null ,timeCards.DoDelete());
      System.assertEquals(Null ,timeCards.DoSave());

   }
    public static TestMethod void timeViewTest4(){
      Milestone1_Project__c tempproject = new Milestone1_Project__c();
      tempproject.Name = 'Temp';
      insert tempproject;
      Milestone1_Milestone__c tempmilestone = new Milestone1_Milestone__c();
      tempmilestone.Project__c = tempproject.Id;
      insert tempmilestone;
      Milestone1_Task__c temptask = new Milestone1_Task__c();
      temptask.Project_Milestone__c = tempmilestone.Id;
      insert temptask;
      Milestone1_Time__c temp = new Milestone1_Time__c();
      temp.Project_Task2__c = temptask.Id;
      temp.Date__c = Date.today().addDays(3);
//      temp.WeekStartDate = Date.today();
      insert temp;
      WeeklyTimecards timeCards = new WeeklyTimecards();
      timeCards.WeekStartDate = Date.today();
      WeeklyTimecards.Timecard c = timeCards.getNewTimecard();
      c.SelectedTask = temp.Project_Task2__c;
      System.debug(c);
      c.getTotalHours();
      c.getMileStones();
      c.getTasks();
      timeCards.DoLoad();
      timeCards.SelectedIndex = 0;
      timeCards.getNewTimecard();
      System.assertEquals(Null ,timeCards.DoNothing());
      System.assertEquals(Null ,timeCards.DoAddRow());
      System.assertEquals(Null ,timeCards.DoCancel());
      System.assertEquals(Null ,timeCards.DoPreviousWeek());
      System.assertEquals(Null ,timeCards.DoNextWeek());
      System.assertEquals(Null ,timeCards.DoDelete());
      System.assertEquals(Null ,timeCards.DoSave());

   }
    public static TestMethod void timeViewTest5(){
      Milestone1_Project__c tempproject = new Milestone1_Project__c();
      tempproject.Name = 'Temp';
      insert tempproject;
      Milestone1_Milestone__c tempmilestone = new Milestone1_Milestone__c();
      tempmilestone.Project__c = tempproject.Id;
      insert tempmilestone;
      Milestone1_Task__c temptask = new Milestone1_Task__c();
      temptask.Project_Milestone__c = tempmilestone.Id;
      insert temptask;
      Milestone1_Time__c temp = new Milestone1_Time__c();
      temp.Project_Task2__c = temptask.Id;
      temp.Date__c = Date.today().addDays(4);
//      temp.WeekStartDate = Date.today();
      insert temp;
      WeeklyTimecards timeCards = new WeeklyTimecards();
      timeCards.WeekStartDate = Date.today();
      WeeklyTimecards.Timecard c = timeCards.getNewTimecard();
      c.SelectedTask = temp.Project_Task2__c;
      System.debug(c);
      c.getTotalHours();
      c.getMileStones();
      c.getTasks();
      timeCards.DoLoad();
      timeCards.SelectedIndex = 0;
      timeCards.getNewTimecard();
      System.assertEquals(Null ,timeCards.DoNothing());
      System.assertEquals(Null ,timeCards.DoAddRow());
      System.assertEquals(Null ,timeCards.DoCancel());
      System.assertEquals(Null ,timeCards.DoPreviousWeek());
      System.assertEquals(Null ,timeCards.DoNextWeek());
      System.assertEquals(Null ,timeCards.DoDelete());
      System.assertEquals(Null ,timeCards.DoSave());

   }
    public static TestMethod void timeViewTest6(){
      Milestone1_Project__c tempproject = new Milestone1_Project__c();
      tempproject.Name = 'Temp';
      insert tempproject;
      Milestone1_Milestone__c tempmilestone = new Milestone1_Milestone__c();
      tempmilestone.Project__c = tempproject.Id;
      insert tempmilestone;
      Milestone1_Task__c temptask = new Milestone1_Task__c();
      temptask.Project_Milestone__c = tempmilestone.Id;
      insert temptask;
      Milestone1_Time__c temp = new Milestone1_Time__c();
      temp.Project_Task2__c = temptask.Id;
      temp.Date__c = Date.today().addDays(5);
//      temp.WeekStartDate = Date.today();
      insert temp;
      WeeklyTimecards timeCards = new WeeklyTimecards();
      timeCards.WeekStartDate = Date.today();
      WeeklyTimecards.Timecard c = timeCards.getNewTimecard();
      c.SelectedTask = temp.Project_Task2__c;
      System.debug(c);
      c.getTotalHours();
      c.getMileStones();
      c.getTasks();
      timeCards.DoLoad();
      timeCards.SelectedIndex = 0;
      timeCards.getNewTimecard();
      System.assertEquals(Null ,timeCards.DoNothing());
      System.assertEquals(Null ,timeCards.DoAddRow());
      System.assertEquals(Null ,timeCards.DoCancel());
      System.assertEquals(Null ,timeCards.DoPreviousWeek());
      System.assertEquals(Null ,timeCards.DoNextWeek());
      System.assertEquals(Null ,timeCards.DoDelete());
      System.assertEquals(Null ,timeCards.DoSave());

   }
    public static TestMethod void timeViewTest7(){
      Milestone1_Project__c tempproject = new Milestone1_Project__c();
      tempproject.Name = 'Temp';
      insert tempproject;
      Milestone1_Milestone__c tempmilestone = new Milestone1_Milestone__c();
      tempmilestone.Project__c = tempproject.Id;
      insert tempmilestone;
      Milestone1_Task__c temptask = new Milestone1_Task__c();
      temptask.Project_Milestone__c = tempmilestone.Id;
      temptask.Task_Type__c = 'Billable';
      temptask.Name = 'temp';
      temptask.Complete__c = false;
      insert temptask;
      Milestone1_Time__c temp = new Milestone1_Time__c();
      temp.Project_Task2__c = temptask.Id;
      temp.Date__c = Date.today().addDays(6);
      insert temp;
      WeeklyTimecards timeCards = new WeeklyTimecards();
      timeCards.WeekStartDate = Date.today();
      WeeklyTimecards.Timecard c = timeCards.getNewTimecard();
      c.SelectedTask = temp.Project_Task2__c;
      System.debug(c);
      c.getTotalHours();
      c.getMileStones();
      c.getTasks();
      timeCards.DoLoad();
      timeCards.DoSave();
      System.assertEquals(temptask.Task_Type__c, c.getTaskType());
      System.assertEquals(temptask.Name, c.selectedTaskName);
      System.assertEquals(temptask.Complete__c, c.isComplete);
   }
      public static TestMethod void timeViewTest8(){
      Milestone1_Project__c tempproject = new Milestone1_Project__c();
      tempproject.Name = 'Temp';
      insert tempproject;
      Milestone1_Milestone__c tempmilestone = new Milestone1_Milestone__c();
      tempmilestone.Project__c = tempproject.Id;
      insert tempmilestone;
      Milestone1_Task__c temptask = new Milestone1_Task__c();
      temptask.Project_Milestone__c = tempmilestone.Id;
      temptask.Task_Type__c = 'Billable';
      temptask.Name = 'temp';
      temptask.Complete__c = false;
      insert temptask;

      List<Milestone1_Time__c> times = new List<Milestone1_Time__c>{
            new Milestone1_Time__c(
                  Project_Task2__c = temptask.Id,
                  Date__c = Date.today().addDays(0),
                  Hours__c = 5
            ),
            new Milestone1_Time__c(
                  Project_Task2__c = temptask.Id,
                  Date__c = Date.today().addDays(1),
                  Hours__c = 5
            ),
            new Milestone1_Time__c(
                  Project_Task2__c = temptask.Id,
                  Date__c = Date.today().addDays(2),
                  Hours__c = 5
            ),
            new Milestone1_Time__c(
                  Project_Task2__c = temptask.Id,
                  Date__c = Date.today().addDays(3),
                  Hours__c = 5
            ),
            new Milestone1_Time__c(
                  Project_Task2__c = temptask.Id,
                  Date__c = Date.today().addDays(4),
                  Hours__c = 5
            ),
            new Milestone1_Time__c(
                  Project_Task2__c = temptask.Id,
                  Date__c = Date.today().addDays(5),
                  Hours__c = 5
            ),
            new Milestone1_Time__c(
                  Project_Task2__c = temptask.Id,
                  Date__c = Date.today().addDays(6),
                  Hours__c = 5
            ),
            new Milestone1_Time__c(
                  Project_Task2__c = temptask.Id,
                  Date__c = Date.today().addDays(7),
                  Hours__c = 5
            )
      };
      insert times;

      Test.startTest();
      WeeklyTimecards timeCards = new WeeklyTimecards();
      timeCards.WeekStartDate = Date.today();
      WeeklyTimecards.Timecard c = timeCards.getNewTimecard();
      c.SelectedTask = times.get(0).Project_Task2__c;
      System.debug(c);
      c.TimeSun = times.get(1);
      c.TimeMon = times.get(2);
      c.TimeTue = times.get(3);
      c.TimeWed = times.get(4);
      c.TimeThu = times.get(5);
      c.TimeFri = times.get(6);
      c.TimeSat = times.get(7);
      c.getTotalHours();
      c.getMileStones();
      c.getTasks();
   }
}