objects/Milestone_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Case_Milestone_ID__c</fullName>
        <label>Case Milestone ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Milestone Exceptions</relationshipLabel>
        <relationshipName>Milestone_Exceptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Proposed_Target_Date__c</fullName>
        <label>Proposed Target Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Product Quality/Delivery</fullName>
                </value>
                <value>
                    <fullName>PS Delivery</fullName>
                </value>
                <value>
                    <fullName>3rd Party Issue</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Milestone Exception</label>
    <nameField>
        <displayFormat>ME-{00000}</displayFormat>
        <label>Milestone Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseMilestoneExceptionEditTests.cls
@IsTest(seealldata=true)
private class CaseMilestoneExceptionEditTests {
    @IsTest
    private static void integrationTest () {
        Account acc = TestDataFactory.createAccount();
        Case c = TestDataFactory.createCase(null);
        c.Subject = 'Test Case with Entitlement';
        c.AccountId = acc.id;
        c.slaStartDate=system.now();
        update c;
        User u = new User(
             ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
             LastName = 'last',
             Email = 'testImagine@ImagineTest.com',
             Username = 'testImagine@ImagineTest.com' + System.currentTimeMillis(),
             CompanyName = 'TEST',
             Title = 'title',
             Alias = 'alias',
             TimeZoneSidKey = 'America/Los_Angeles',
             EmailEncodingKey = 'UTF-8',
             LanguageLocaleKey = 'en_US',
             LocaleSidKey = 'en_US',
             ManagerId = UserInfo.getUserId()
        );
        Test.startTest();
        system.runAs(u){
            List<CaseMileStone> lstCMS = [select id from CaseMilestone limit 1];
            system.debug('@@@ issue'+[select StartDate, TargetDate, MilestoneType.Name from CaseMilestone where CaseId = :c.id and MilestoneType.Name not in ('Update', 'Automated Update') and IsCompleted = false]);
            Milestone_Exception__c me = new Milestone_Exception__c(Case__c = c.Id, Case_Milestone_ID__c = lstCMS[0].Id );
            ApexPages.StandardController sc = new ApexPages.StandardController(me);
            CaseMilestoneExceptionEdit controller = new CaseMilestoneExceptionEdit(sc);
            controller.sobj.Type__c = 'test';
            controller.sobj.Description__c = 'Test';
            controller.save();
            Test.stopTest(); 
        }
    }
    
    @IsTest
    private static void updateMileStoneException () {
        Account acc = TestDataFactory.createAccount();
        Case c = TestDataFactory.createCase(null);
        c.Subject = 'Test Case with Entitlement';
        c.AccountId = acc.id;
        c.slaStartDate=system.now();
        update c;
        List<CaseMileStone> lstCMS = [select id from CaseMilestone limit 1];
        Datetime dt = Datetime.now();
        dt = dt.addDays(30);
        Milestone_Exception__c me = new Milestone_Exception__c(
            Case__c = c.Id, 
            Status__c ='Draft', 
            Case_Milestone_ID__c = lstCMS[0].Id, 
            type__c='Customer',
            Proposed_Target_Date__c = dt
        );
        insert me;
        Test.startTest();
        Milestone_Exception__c upMilestoneExp = [SELECT Id,Status__c from Milestone_Exception__c where id=:me.Id];
        upMilestoneExp.Status__c = 'Approved';
        update upMilestoneExp;
        Test.stopTest();
    }
}