objects/Milestone1_Time__c.object
<CustomObject>
    <description>This object is a replica of the Time object(Miilestone1 Unmanaged package)</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>The date the time was incurred. Defaults to today if left blank.</inlineHelpText>
        <label>Date Incurred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <inlineHelpText>The number of hours charged. Note: This cannot be more than 1 day (24 hours).</inlineHelpText>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incurred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user who incurred the time being charged. Defaults to current user if left blank.</inlineHelpText>
        <label>Service Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_TimesIncurred</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Type__c</fullName>
        <label>Time Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time</label>
    <nameField>
        <label>Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseTimeEntryController.cls
public class CaseTimeEntryController {
    
    public Milestone1_Time__c timeEntry {get; set;}
    public Integer minutes {get; set;}
    private Id caseId; 

    public CaseTimeEntryController(ApexPages.StandardController stdCon) {
        caseId = stdCon.getId();
        init();
    }
     
    private void init() {
        timeEntry = new Milestone1_Time__c();
        timeEntry.Case__c = caseId;
        timeEntry.Date__c = Date.today();
        timeEntry.Incurred_By__c = UserInfo.getUserId();
        timeEntry.Billable__c = true;
        timeEntry.Time_Type__c = '';
        timeEntry.Hours__c = 0;
        minutes = 0;
    }
    
    public void save(){
        if((timeEntry.Hours__c == null || timeEntry.Hours__c == 0) && 
          (minutes == null || minutes == 0)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.WARNING, 'Please enter hours or minutes'));
        } else {
            if(timeEntry.Hours__c == null) {
                timeEntry.Hours__c = 0;
            }
            if(minutes != null) timeEntry.Hours__c += (minutes / 60.0);
            insert timeEntry;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO , 'Time entry saved successfully.'));
            init();
        }
    }
    
    public void cancel(){
        init();
    } 
}