objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>This object is a replica of the Old Milestone object(Miilestone1 Unmanaged package)</description>
    <fields>
        <fullName>CHK_Customer_Satisfaction_Contact_Info__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Proforce CHK 11/2014</description>
        <inlineHelpText>Customer Satisfaction Contact Information: (Name &amp; email in Stakeholder list)</inlineHelpText>
        <label>Customer Satisfaction Contact Info</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHK_Customer_satisfaction_survey_del__c</fullName>
        <description>Proforce CHK 11/2014</description>
        <inlineHelpText>Customer satisfaction survey delivered</inlineHelpText>
        <label>Customer satisfaction survey delivered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Project_Milestones2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Old Milestone</label>
    <nameField>
        <label>Old Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Old Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Milestone1_Project__c.object
<CustomObject>
    <description>This object is a replica of the Old Project object(Miilestone1 Unmanaged package)</description>
    <label>Old Project</label>
    <nameField>
        <label>Old Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Old Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3PV System Engineer</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Customer Contact</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Project Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Contacts</relationshipLabel>
        <relationshipName>Project_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project2__c</fullName>
        <label>Project2</label>
        <referenceTo>MPM4_BASE__Milestone1_Project__c</referenceTo>
        <relationshipLabel>Project Contacts</relationshipLabel>
        <relationshipName>Project_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Contact</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Project Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestCustomerSatisfactionSurveyTrigger.cls
@isTest
public class TestCustomerSatisfactionSurveyTrigger {
    static testmethod void TestCustomerSatisfactionSurveyTrigger()
    {
        RecordType MSRecType = [select Id from RecordType where SobjectType = 'Milestone1_Milestone__c' and Name = 'Standard Milestone'];

        Milestone1_Project__c testProject = new Milestone1_Project__c();
        testProject.Name = 'Test Project1';
        Insert testProject;
        
        Contact Con= new Contact();
        Con.LastName = 'My';
        Con.FirstName = 'Name';        
        Con.Email = 'MyName@email.com';
        Insert Con;
        
        Project_Contact__c testContact = new Project_Contact__c();
        testContact.Contact_Type__c = 'Customer Satisfaction Contact';
        testContact.Contact__c = Con.Id;
        testContact.Project2__c = testProject.Id;
        Insert testContact;
        
        Milestone1_Milestone__c testMilestone = new Milestone1_Milestone__c();
        testMilestone.Project__c = testProject.id;
        testMilestone.RecordTypeId = MSRecType.Id;
        testMilestone.Name = 'Test Milestone';
        
        testMilestone.CHK_Customer_Satisfaction_Contact_Info__c = True;
        testMilestone.CHK_Customer_satisfaction_survey_del__c = Date.today();
        
        insert testMilestone;
    }
}