objects/Milestone1_Time__c.object
<CustomObject>
    <description>This object is a replica of the Time object(Miilestone1 Unmanaged package)</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <inlineHelpText>The number of hours charged. Note: This cannot be more than 1 day (24 hours).</inlineHelpText>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time</label>
    <nameField>
        <label>Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseRollupUpdater.cls
global class CaseRollupUpdater implements Database.Batchable<SObject>, Schedulable {
    
    global String iteratorQuery = 
        'select Id, Total_Time_Entered__c, Total_Hours_Incurred__c '+
        'from Case where LastModifiedDate >= last_n_days:7';
    
   	global String aggregateQuery = 
        'select Case__c Id, '+
        'sum(Hours__c) Total_Time_Entered__c, '+
        'sum(Hours__c) Total_Hours_Incurred__c  '+
        'from Milestone1_Time__c where Case__c in :scopeIds group by Case__c';
    
    global Set<String> destinationFields = new Set<String>{'Total_Time_Entered__c', 'Total_Hours_Incurred__c'};
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(iteratorQuery);
	}
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        Map<Id, sObject> scopeMap = new Map<Id, sObject>(scope);
        Set<Id> scopeIds = scopeMap.keySet();
        Map<Id, sObject> toUpdate = new Map<Id, sObject>();
        for (AggregateResult ar : Database.query(aggregateQuery)) {
            System.debug('AggregateResult: ' + ar);
            sObject c = scopeMap.get((String)ar.get('Id'));
            for (String f : destinationFields) {
                Decimal aggregateValue = (Decimal)ar.get(f);
                if ((Decimal)c.get(f) != aggregateValue) {
                    c.put(f, aggregateValue);
                    toUpdate.put(c.Id, c);
                }
            }
        }
        update toUpdate.values();
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
    public static void run (Integer daysBackToProcess) {
        CaseRollupUpdater b = new CaseRollupUpdater();
        b.iteratorQuery = b.iteratorQuery.replace('last_n_days:7', 'last_n_days:' + daysBackToProcess);
		Database.executeBatch(b, 50);
    }
	
    public static void run () {
		run(7);
    }
    
    global void execute(SchedulableContext sc) {
        CaseRollupUpdater.run();
    }
}