objects/MPM_Project_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Displays either the user or contact email based on the record type.</description>
        <formula>IF(RecordType.DeveloperName = &quot;Contact&quot;, 
 Resource__r.MPM4_BASE__Contact__r.Email,
 Resource__r.MPM4_BASE__User__r.Email 
)</formula>
        <inlineHelpText>Displays either the user or contact email based on the record type.</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>IF(RecordType.DeveloperName = &quot;Contact&quot;, 
Resource__r.MPM4_BASE__Contact__r.Phone, 
Resource__r.MPM4_BASE__User__r.Phone 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MPM4_BASE__Milestone1_Project__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>MPM_Project_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <errorMessage>MPM+ Project Resource: The selected resource does not match the record type, e.g. when the record type is Contact, the resource must lookup to a Contact as well.</errorMessage>
            <filterItems>
                <field>MPM4_BASE__Milestone1_Resource__c.MPM4_BASE__Contact__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>User</value>
            </filterItems>
            <filterItems>
                <field>MPM4_BASE__Milestone1_Resource__c.MPM4_BASE__User__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Contact</value>
            </filterItems>
            <infoMessage>Displayed resources has been limited corresponding to the record type (User/Contact).</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MPM4_BASE__Milestone1_Resource__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>MPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Project Manager</fullName>
                </value>
                <value>
                    <fullName>Secondary Project Manager</fullName>
                </value>
                <value>
                    <fullName>Field Engineer</fullName>
                </value>
                <value>
                    <fullName>Enterprise Solutions Manager</fullName>
                </value>
                <value>
                    <fullName>3PV System Engineer</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Customer Contact</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MPM+ Project Resource</label>
    <nameField>
        <displayFormat>MPR-{000000}</displayFormat>
        <label>MPM+ Project Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPM+ Project Resources</pluralLabel>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MPM4_ProjectRelatedToEmailCtrl.cls
public class MPM4_ProjectRelatedToEmailCtrl {
 
    @AuraEnabled
    public static ProjectsWrapper findMPM4Projects(List<String> emails, Boolean isLimited) {
        
        Set<ID> accountIds = new Set<ID>(); 
        for(Contact c : [SELECT Name, AccountID FROM Contact WHERE Contact.Email IN :emails]){
            accountIds.add(c.AccountID);
        }
        
        Set<ID> projectIds = new Set<ID>();  
        for(MPM_Project_Resource__c mpr : [SELECT Id, Phone__c, Project__c, Resource__c, Email__c, Type__c FROM MPM_Project_Resource__c where Email__c IN :emails]){
            projectIds.add(mpr.project__c);
        }
        
        
        List<Schema.FieldSetMember> fieldset = Schema.SObjectType.MPM4_BASE__Milestone1_Project__c.fieldSets.MPM4_Project_Outlook_Component_Fields.getFields();
        
        Set<String> fieldsToQuery = new Set<String>{'Name', 'Id'};
        String query = 'SELECT ';
        
        for(Schema.FieldSetMember f : fieldset){
            fieldsToQuery.add(f.getFieldPath());
            
        } 
        
        for(String field : fieldsToQuery){
            query += 'FORMAT(' + field + '), ';
        } 
        query = query.removeEnd(', ');
        
        if(isLimited){
            query += ' FROM MPM4_BASE__Milestone1_Project__c WHERE MPM4_BASE__Account__c in :accountIds OR Id in :projectIds  ORDER BY lastmodifieddate DESC LIMIT 5';    
        }else{
             query += ' FROM MPM4_BASE__Milestone1_Project__c WHERE MPM4_BASE__Account__c in :accountIds OR Id in :projectIds  ORDER BY lastmodifieddate DESC';    
        }
        
        
        AggregateResult[] groupedResults = [SELECT count(id) total FROM MPM4_BASE__Milestone1_Project__c WHERE MPM4_BASE__Account__c in :accountIds OR Id in :projectIds];
        Integer count = Integer.valueOf(groupedResults[0].get('total'));
        
        ProjectsWrapper pw = new ProjectsWrapper();
        pw.count = count;
        pw.projects = Database.query(query);
        return pw;
    }
    
    @AuraEnabled
    public static ListView getListViews() {
        return [SELECT Id, Name FROM ListView WHERE SobjectType = 'MPM4_BASE__Milestone1_Project__c' and name='All' LIMIT 1];
    }
    @AuraEnabled
    public static string getFieldsetFieldNames() {
        List<fieldNamePair> names = new List<fieldNamePair>();
 
        List<Schema.FieldSetMember> fieldset =  Schema.SObjectType.MPM4_BASE__Milestone1_Project__c.fieldSets.MPM4_Project_Outlook_Component_Fields.getFields();
        
        for(Schema.FieldSetMember f : fieldset){ 
            names.add(new fieldNamePair(f));
        } 
        return JSON.serialize(names);
    }   
    
    private class fieldNamePair{
      String label = '';
      String apiname = '';
      public fieldNamePair(Schema.FieldSetMember fs){
        label = fs.getLabel();
        apiname = fs.getFieldPath();
 
      }
    }

    public class ProjectsWrapper{
        @AuraEnabled
        public List<MPM4_BASE__Milestone1_Project__c> projects{get;set;}

        @AuraEnabled
        public Integer count {get;set;}
        
    }
}