objects/MPM_Project_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Resources</relationshipLabel>
        <relationshipName>MPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MPM4_BASE__Milestone1_Project__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>MPM_Project_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MPM+ Project Resource</label>
    <nameField>
        <displayFormat>MPR-{000000}</displayFormat>
        <label>MPM+ Project Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MPM+ Project Resources</pluralLabel>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MPM4_ProjectRelatedToEmailCtrlTest.cls
@isTest
public class MPM4_ProjectRelatedToEmailCtrlTest {

	@testsetup
	public static void generateData(){
		RecordType rtProjectContact = [select id from recordtype where sobjecttype='MPM_Project_Resource__c' and name ='Contact' limit 1];
		Account acc = TestDataFactory.createAccount();
		Contact con = TestDataFactory.createContact(acc);
		con.email = 'sample@demo.com';
		update con;


		MPM4_BASE__Milestone1_Project__c milestone = new MPM4_BASE__Milestone1_Project__c();
		milestone.MPM4_BASE__Account__c = acc.id;
		insert milestone;

		MPM_Project_Resource__c  project = new MPM_Project_Resource__c();
        project.Contact__c = con.id;
		project.recordTypeId = rtProjectContact.Id;
		project.Project__c = milestone.id;
		insert project;

	}

	@isTest
	public static void testProjects(){
		List<String> lstEmails = new List<String>();
		lstEmails.add('sample@demo.com');
		MPM4_ProjectRelatedToEmailCtrl.ProjectsWrapper projWrapper = MPM4_ProjectRelatedToEmailCtrl.findMPM4Projects(lstEmails, true);
		system.assert(projWrapper.count == 1);
		system.assert(projWrapper.projects.size() == 1);
		MPM4_ProjectRelatedToEmailCtrl.getListViews();
		MPM4_ProjectRelatedToEmailCtrl.getFieldsetFieldNames();
	}
}