objects/Time_Reporting__c.object
<CustomObject>
    <description>Time Reporting</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charge_Code__c</fullName>
        <label>Charge Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Internal Project</fullName>
                </value>
                <value>
                    <fullName>Leave of Absence</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paid Time Off (PTO)</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Incurred__c</fullName>
        <label>Date Incurred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incurred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incurred By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MPM4_Time__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MPM4 Time</label>
        <referenceTo>MPM4_BASE__Milestone1_Time__c</referenceTo>
        <relationshipLabel>Time Reporting</relationshipLabel>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MS_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MS Task</label>
        <referenceTo>MPM4_BASE__Milestone1_Task__c</referenceTo>
        <relationshipLabel>Time Reporting</relationshipLabel>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>MPM4_BASE__Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Time Reporting</relationshipLabel>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MPM4_BASE__Milestone1_Project__c</referenceTo>
        <relationshipLabel>Time Reporting</relationshipLabel>
        <relationshipName>Time_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Id__c</fullName>
        <externalId>true</externalId>
        <label>Time Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Source__c</fullName>
        <label>Time Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Type__c</fullName>
        <label>Time Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Reporting</label>
    <nameField>
        <label>Time Reporting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchTimeReportingProjectTaskTime.cls
global class BatchTimeReportingProjectTaskTime implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    public String upsertErrors = '';
    public Integer batchSize = 200;
    public Datetime asOf = Datetime.now().addHours(-24);
    
    /** 
     * @description Schedulable interface entrypoint
     */
    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, this.batchSize);
    }
    
    /**
     * @description query for records which are not yet in the time reporting table or are out of date
     */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // TODO Id not in (select MPM4_Time__c from Time_Reporting__c)
        return Database.getQueryLocator([
            SELECT Id, Name, Billable__c, Category__c, Charge_Code__c, MPM4_BASE__Date__c,
            MPM4_BASE__Description__c, MPM4_BASE__Hours__c, MPM4_BASE__Incurred_By__c, Time_Type__c,
            MPM4_BASE__Project_Task__c, MPM4_BASE__Project_Task__r.MPM4_BASE__Project_Milestone__c,
            MPM4_BASE__Project_Task__r.MPM4_BASE__Project_Lookup__c
            FROM MPM4_BASE__Milestone1_Time__c 
            WHERE LastModifiedDate >= :asOf
	        OR SystemModstamp >= :asOf
        ]);
    }
    
    /**
     * @description upsert a copy of the record into time reporting
     */
    global void execute(Database.BatchableContext bc, List<MPM4_BASE__Milestone1_Time__c> mpmTimeList) {
        List<Time_Reporting__c> toUpsert = new List<Time_Reporting__c>();
        for(MPM4_BASE__Milestone1_Time__c mst : mpmTimeList) {
            Time_Reporting__c timeReporting = new Time_Reporting__c();
            timeReporting.MPM4_Time__c = mst.Id;
            timeReporting.Time_Id__c = mst.Id;
            timeReporting.Name = mst.Name;
            timeReporting.Billable__c = mst.Billable__c;
            timeReporting.Category__c = mst.Category__c;
            timeReporting.Charge_Code__c = mst.Charge_Code__c;
            timeReporting.Date_Incurred__c = mst.MPM4_BASE__Date__c;
            timeReporting.Description__c = mst.MPM4_BASE__Description__c;
            timeReporting.Hours__c = mst.MPM4_BASE__Hours__c;
            timeReporting.Incurred_By__c = mst.MPM4_BASE__Incurred_By__c;
            timeReporting.Time_Type__c = mst.Time_Type__c;
            timeReporting.MS_Task__c = mst.MPM4_BASE__Project_Task__c;
            timeReporting.Milestone__c = mst.MPM4_BASE__Project_Task__r.MPM4_BASE__Project_Milestone__c;
            timeReporting.Project__c = mst.MPM4_BASE__Project_Task__r.MPM4_BASE__Project_Lookup__c;
            if (timeReporting.Project__c != null) timeReporting.Time_Source__c = 'Project';
            toUpsert.add(timeReporting);
        }
        handleErrors(Database.upsert(toUpsert, Time_Reporting__c.Fields.Time_Id__c, false), toUpsert);
        
        deleteOrphaned();
    }
    
    /**
     * @description send email with errors if any occurred
     */
    global void finish(Database.BatchableContext bc){
        
        deleteOrphaned();
        
        if(String.isBlank(upsertErrors)) return;
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage() ;
        String[] toAddresses = new String[] {'jsullivan+imagine@cloudanswers.com'};
        // TODO add person who scheduled the batch?
        mail.setToAddresses(toAddresses);
        mail.setSubject('[BatchTimeReportingProjectTaskTime] Errors');
        String body = 'Errors:\n\n' + upsertErrors;
        mail.setPlainTextBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		System.assert(!Test.isRunningTest(), this.upsertErrors);
    }
    
    /**
     * @description deleted records once linked to this object 
     */
    private void deleteOrphaned () {
        String idLike = MPM4_BASE__Milestone1_Time__c.sobjecttype.getDescribe().getKeyPrefix() + '%';
        List<Time_Reporting__c> toDelete = [
            select Id 
            from Time_Reporting__c
            where Time_Id__c like :idLike
            and MPM4_Time__c not in (select Id from MPM4_BASE__Milestone1_Time__c)
            limit :this.batchSize
        ];
        handleErrors(Database.delete(toDelete, false), toDelete);
    }
    
    /**
     * @description finds errors in dml results and appends them to an error email body
     * @param dmlResultList the resulting list of objects to process
     * @param records the records that were sent to the dml call
     */
    private void handleErrors (List<Object> dmlResultList, List<SObject> records) {
        System.assertEquals(dmlResultList.size(), records.size(), 'different counts on records and dml results');
        for (Integer i=0; i < dmlResultList.size(); i++) {
            SObject sobj = records[i];
            List<Database.Error> errors = new List<Database.Error>();
            Database.UpsertResult ur = dmlResultList[i] instanceOf Database.UpsertResult ? (Database.UpsertResult)dmlResultList[i] : null;
            if (ur != null) errors.addAll(ur.getErrors());
            Database.DeleteResult dr = dmlResultList[i] instanceOf Database.DeleteResult ? (Database.DeleteResult)dmlResultList[i] : null;
            if (dr != null) errors.addAll(dr.getErrors());
            for(Database.Error e : errors) {
                upsertErrors += '[' + sobj.Id + '] ' + e + '\n';
                // upsertErrors += sobj + '\n';
            }
        }
    }
}