objects/Topic__c.object
<CustomObject>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Epic</label>
        <referenceTo>Epics__c</referenceTo>
        <relationshipName>Topics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Topic_DEPRECIATED</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <fields>
        <fullName>As_A__c</fullName>
        <label>As A</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Burned__c</fullName>
        <label>Burned</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependencies__c</fullName>
        <label>Dependencies</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Epic</label>
        <referenceTo>Epics__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Harris_Broadcast_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Must Have</fullName>
                </value>
                <value>
                    <fullName>1 - High</fullName>
                </value>
                <value>
                    <fullName>2 - Med</fullName>
                </value>
                <value>
                    <fullName>3 - Low</fullName>
                </value>
                <value>
                    <fullName>4 - Wishlist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_Want__c</fullName>
        <label>Test Scenario</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LOE__c</fullName>
        <label>Imagine LOE</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Or_Domain__c</fullName>
        <label>Object Or Domain</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Type of Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
                <value>
                    <fullName>Production Defect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <formula>if( ISPICKVAL( Phase__c, &quot;1&quot;), &quot;MAR&quot;, &quot;JUL&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Release</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>So_That__c</fullName>
        <label>Expected Result</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Topic</label>
        <referenceTo>Topic__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/userStoryController.cls
public with sharing class userStoryController {


    public List<cUserStory> uslist2 {get; set;}

    public User_Story__c[] uslist {get;set;}
    public List<User_Story__c> getUserStories() {
           uslist2 = new List<cUserStory>();
           uslist = [select id, Name, As_A__c,  I_Want__c,  So_That__c,     Epic__c, Topic__c, Phase__c,    LOE__c, Harris_Broadcast_Priority__c,   Object_Or_Domain__c, Notes__c, Functional_Area__c, Dependencies__c, Burned__c  from User_Story__c];
           for(User_Story__c c: uslist) {
               uslist2.add(new cUserStory(c));
           }    
        return uslist;
    }   
    public List<cUserStory> getUserStories2() {
           uslist2 = new List<cUserStory>();
           uslist = [select id, Name, As_A__c,  I_Want__c,  So_That__c, Release__c,     Epic__c, Topic__c, Phase__c,    LOE__c, Harris_Broadcast_Priority__c,   Object_Or_Domain__c, Notes__c, Functional_Area__c, Dependencies__c, Burned__c  from User_Story__c];
           for(User_Story__c c: uslist) {
               uslist2.add(new cUserStory(c));
           }    
        return uslist2;
    }      
    public PageReference process() {
        try
        {
            List<User_Story__c > selectedUsts = new List<User_Story__c >(); 
            //We will cycle through our list of cContacts and will check to see if the selected property is set to true, if it is we add the Contact to the selectedContacts list
            for(cUserStory cUs: getUserStories2()) {
                if(cUs.selected == true) {
                    selectedUsts.add(cUs.ust);
                    cUs.selected = false;
                }
            }   

        // Now we have our list of selected contacts and can perform any type of logic we want, sending emails, updating a field on the Contact, etc
        
 
        for(User_Story__c con: selectedUsts) {
            system.debug('BLAHBLAH' + con.id + '--' + con.name  );
            update con;
            System.debug('Update completed: ');             
        }                
        } catch(Exception ex){}
        
        //PageReference pageRef = new PageReference('/apex/testcode1');
        //pageRef.setRedirect(true);
        //        return pageRef;   
        return null;           
    }  
    public class cUserStory {
        public User_Story__C ust {get; set;}
        public Boolean selected {get; set;}

        //This is the contructor method. When we create a new cContact object we pass a Contact that is set to the con property. We also set the selected value to false
        public cUserStory(User_Story__C u) {
            ust = u;
            selected = false;
        }
    }      
     
}